version: "3.3"
name: concertim
services:
  visualisation:
    image: concertim-visualisation-app
    volumes:
      - static-content:{{static_content_mount}}
      - type: bind
        source: "{{ct_etc_dir}}"
        target: "{{ct_etc_mount}}"
    env_file:
      - secrets/secrets.env
    environment:
      - METRIC_DAEMON_URL=http://metrics:3000
      - POSTGRES_HOST=db
      - CREDENTIALS_CONTENT_PATH={{credentials_path}}
    expose:
      - 7000
    depends_on:
      - db
    networks:
      concertim-net: {}

  metrics:
    image: concertim-metric-reporting-daemon
    volumes:
      - rrd-data:/var/lib/ganglia/rrds
      - type: bind
        source: "{{ct_etc_dir}}"
        target: "{{ct_etc_mount}}"
    env_file:
      - secrets/secrets.env
    expose:
      - 3000
    networks:
      concertim-net: {}

  proxy:
    image: concertim-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - static-content:{{static_content_mount}}
    depends_on:
      - visualisation
      - metrics
    networks:
      concertim-net: {}

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    env_file:
      - secrets/secrets.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      concertim-net: {}

volumes:
  db-data:
  rrd-data:
  static-content:

networks:
  concertim-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
