version: "3.3"
name: concertim
services:
  visualisation:
    image: concertim-visualisation-app
    volumes:
      - static-content:{{static_content_mount}}
      - type: bind
        source: "{{ct_etc_dir}}"
        target: "{{ct_etc_mount}}"
    env_file:
      - secrets/secrets.env
    environment:
      - METRIC_DAEMON_URL=http://metric_reporting_daemon:3000
      - POSTGRES_HOST=db
      - CREDENTIALS_CONTENT_PATH={{credentials_path}}
    expose:
      - 7000
    depends_on:
      - db
    networks:
      concertim-net: {}

  metric_reporting_daemon:
    image: concertim-metric-reporting-daemon
    volumes:
      - rrd-data:/var/lib/ganglia/rrds
      - type: bind
        source: "{{ct_etc_dir}}"
        target: "{{ct_etc_mount}}"
    env_file:
      - secrets/secrets.env
    expose:
      - 3000
    networks:
      concertim-net: {}

  cluster_builder: 
    image: concertim-cluster-builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    expose:
      - 42378
    ports:
      - "{{cluster_builder_host_interface}}:{{cluster_builder_host_port}}:42378"
    volumes:
      - "{{ct_cluster_builder_share_dir}}/:/app/instance"
    networks:
      concertim-net: {}

  api_server:
    image: concertim-api-server
    expose:
      - 42356
    ports:
      - "{{api_server_host_interface}}:{{api_server_host_port}}:42356"
    volumes:
      - "{{ct_etc_dir}}/openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml"
      - "{{ct_log_dir}}/openstack-service/:/app/var/log/"
      - "{{ct_openstack_service_data_dir}}:/app/var/data/"

  bulk_updates:
    image: concertim-bulk-updates
    volumes:
      - "{{ct_etc_dir}}/openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml"
      - "{{ct_log_dir}}/openstack-service/:/app/var/log/"
      - "{{ct_openstack_service_data_dir}}:/app/var/data/"

  mq_listener:
    image: concertim-mq-listener
    volumes:
      - "{{ct_etc_dir}}/openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml"
      - "{{ct_log_dir}}/openstack-service/:/app/var/log/"
      - "{{ct_openstack_service_data_dir}}:/app/var/data/"

  metrics:
    image: concertim-metrics
    volumes:
      - "{{ct_etc_dir}}/openstack-service/config.yaml:/etc/concertim-openstack-service/config.yaml"
      - "{{ct_log_dir}}/openstack-service/:/app/var/log/"
      - "{{ct_openstack_service_data_dir}}:/app/var/data/"

  proxy:
    image: concertim-proxy
    ports:
      {% if proxy_host_http_port -%}
      - "{{proxy_host_http_interface}}:{{proxy_host_http_port}}:80"
      {% endif -%}
      - "{{proxy_host_https_interface}}:{{proxy_host_https_port}}:443"
    volumes:
      - static-content:{{static_content_mount}}
    depends_on:
      - visualisation
      - metric_reporting_daemon
    networks:
      concertim-net: {}

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    env_file:
      - secrets/secrets.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      concertim-net: {}

volumes:
  db-data:
  rrd-data:
  static-content:

networks:
  concertim-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
