- name: Install nginx and dependencies
  ansible.builtin.apt:
    name:
      - ssl-cert
      - nginx
      - php8.1-fpm
    state: latest

- name: Write the apache config files
  ansible.builtin.copy:
    src: nginx/
    dest: /etc/nginx/

- name: Disable default sites
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Enable sites
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{item}}
    dest: /etc/nginx/sites-enabled/{{item}}
    state: link
  loop:
    - default-http
    - default-https

- name: Ensure that nginx is started
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
