- name: Generate shared secret
  vars:
    secret_file: "{{ ct_installation_dir }}/ct-metric-reporting-daemon/config/secret"
  block:
    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{item}}"
        owner: root
        group: "{{app_user}}"
        mode: "755"
        state: directory
      loop:
        - "{{ ct_installation_dir }}/ct-metric-reporting-daemon"
        - "{{ ct_installation_dir }}/ct-metric-reporting-daemon/config"

    - name: Created secret
      ansible.builtin.shell:
        cmd: |
          ruby -r securerandom -e 'puts SecureRandom.hex(64)' > {{secret_file}}

    - name: Ensure {{app_user}} can read file
      ansible.builtin.file:
        path: "{{secret_file}}"
        owner: root
        group: "{{app_user}}"
        mode: "640"
