version: "3.3"
services:
  visualisation:
    image: registry.docker.concertim.alces-flight.com/concertim-ui-visualisation
    secrets:
      - db-password
    volumes:
      - static-content:/opt/concertim/opt/ct-visualisation-app/public
      - concertim-etc:/opt/concertim/etc
    environment:
      - METRIC_DAEMON_URL=http://metrics:3000
    expose:
      - 7000
    depends_on:
      - db
    networks:
      concertim-net: {}

  metrics:
    image: registry.docker.concertim.alces-flight.com/concertim-ui-metrics
    volumes:
      - concertim-etc:/opt/concertim/etc
      - rrd-data:/var/lib/ganglia/rrds
    expose:
      - 3000
    networks:
      concertim-net: {}

  proxy:
    image: registry.docker.concertim.alces-flight.com/concertim-ui-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - static-content:/opt/concertim/opt/ct-visualisation-app/public
    depends_on:
      - visualisation
      - metrics
    networks:
      concertim-net: {}

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      concertim-net: {}

volumes:
  db-data:
  rrd-data:
  static-content:
  concertim-etc:

secrets:
  db-password:
    file: secrets/db/password.txt

networks:
  concertim-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
