- name: Install postgresql
  ansible.builtin.apt:
    name: postgresql
    state: present

- name: Update configuration to log to syslog
  ansible.builtin.replace:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: true
  loop:
    - regexp: "#log_destination = 'stderr'"
      replace: "log_destination = 'syslog'"
    - regexp: '#syslog_'
      replace: 'syslog_'

- name: Ensure that postgresql is started
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes

- name: Configure database user
  block:
    - name: Check if {{ app_user }} role exists
      ansible.builtin.command:
        cmd: sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ app_user }}'"
      register: db_user_exist

    - name: Create {{ app_user }} role
      when: db_user_exist.stdout == ""
      ansible.builtin.command:
        cmd: sudo -u postgres createuser {{ app_user }} -S -R -d
