- name: Import APT signing key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgresql repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
    state: present
    filename: postgresql-pgdg

- name: Install postgresql 11
  ansible.builtin.apt:
    name: postgresql-11
    state: present

- name: Update configuration to log to syslog
  ansible.builtin.replace:
    path: /etc/postgresql/11/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    backup: true
  loop:
    - regexp: "#log_destination = 'stderr'"
      replace: "log_destination = 'syslog'"
    - regexp: '#syslog_'
      replace: 'syslog_'
    # - regexp: 'max_connections = 100'
    #   replace: 'max_connections = 145'
    # - regexp: 'shared_buffers = 32MB'
    #   replace: 'shared_buffers = 24MB'

- name: Ensure that postgresql is started
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes

- name: Configure database user
  vars:
    db_user: www-data
  block:
    - name: Check if {{ db_user }} role exists
      ansible.builtin.command:
        cmd: sudo -u postgres psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user }}'"
      register: db_user_exist

    - name: Create {{ db_user }} role
      when: db_user_exist.stdout == ""
      ansible.builtin.command:
        cmd: sudo -u postgres createuser {{ db_user }} -A -R -d
