- name: Write branding.yml
  ansible.builtin.copy:
    dest: "{{ branding_yaml_path }}"
    content: "{{ branding_name }}"
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: "644"

- name: Make directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{app_user}}"
    group: root
    mode: "755"
    state: directory
  loop:
    - "{{ etc_personalty_folder }}"

- name: Copy personality metadata
  ansible.builtin.copy:
    src: personality.yml
    dest: "{{ item }}"
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: "644"
  loop:
    - "{{ etc_personalty_folder }}/personality.yml"
