---
- name: Checkout source directories
  ansible.builtin.git:
    repo: "{{cluster_builder.source.repo}}"
    dest: "{{cluster_builder.install_dir}}"
    # single_branch: yes
    version: "{{cluster_builder.source.commitish}}"
  environment:
    GIT_TERMINAL_PROMPT: 0
  register: cluster_builder_checkout

# We need the following as the directory is owned by root, but not all git
# commands are executed as root.
# XXX Can we remove this somehow?
- name: Workaround git and dubious ownership issues
  ansible.builtin.command:
    cmd: git config --global --add safe.directory "{{cluster_builder.install_dir}}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - path: "{{ct_log_dir}}/cluster-builder"
      owner: root
      group: root
      mode: "755"

- name: Copy cluster type definitions
  vars:
    available_dir: "{{ct_cluster_builder_share_dir}}/cluster-types-available"
    enabled_dir: "{{ct_cluster_builder_share_dir}}/cluster-types-enabled"
    templates_dir: "{{ct_cluster_builder_share_dir}}/templates"
  block:
    - name: Create cluster type definition directories
      ansible.builtin.file:
        path: "{{item}}"
        owner: root
        group: root
        mode: "755"
        state: directory
      loop:
        - "{{available_dir}}"
        - "{{enabled_dir}}"
        - "{{templates_dir}}"

    - name: Copy examples cluster type definitions
      ansible.builtin.copy:
        src: "{{cluster_builder.install_dir}}/examples/{{item.src}}"
        remote_src: true
        dest: "{{item.dest}}"
      loop:
        - src: cluster-types/
          dest: "{{available_dir}}"
        - src: templates/
          dest: "{{templates_dir}}"

    - name: Find available types
      ansible.builtin.find:
        path: "{{available_dir}}"
        depth: 2
        file_type: file
        pattern: "cluster-type.yaml"
        recurse: true
      register: available_types

    - name: Enable all available types
      vars:
        disabled_cluster_types:
          - big-data-analysis
          - big-data-analysis-direct
          - k8s-web-hosting
      ansible.builtin.file:
        src: "../cluster-types-available/{{item.path | dirname | basename}}"
        dest: "{{enabled_dir}}/{{item.path | dirname | basename}}"
        state: link
      loop: "{{ available_types.files }}"
      when: "item.path | dirname | basename not in disabled_cluster_types"

- name: Set git checkout and docker image facts
  vars:
    component: cluster_builder
    install_dir: "{{cluster_builder.install_dir}}"
    force_docker_latest: "{{cluster_builder.source.commitish == 'main'}}"
  import_tasks: gather_git_and_docker_facts.yaml

- name: Build docker image
  vars:
    component: cluster_builder
    force_source: "{{cluster_builder_checkout.changed}}"
    notifications:
      - "Stop cluster_builder container"
  import_tasks: build_docker_image.yaml
