- name: Make installation directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - path: "{{ct_root_dir}}"
      owner: root
      group: root
      mode: "755"

    - path: "{{ct_etc_dir}}"
      owner: root
      group: root
      mode: "755"

    - path: "{{ct_installation_dir}}"
      owner: "{{app_user}}"
      group: "{{app_user}}"
      mode: "755"
