diff -ur number-crunchers.orig/meryl/Makefile number-crunchers/meryl/Makefile
--- number-crunchers.orig/meryl/Makefile	2022-09-29 15:54:28.306754228 +0000
+++ number-crunchers/meryl/Makefile	2022-10-06 12:50:14.329522390 +0000
@@ -1,12 +1,18 @@
 
 SHELL = /bin/sh
-# VER = 1.8
 VER = 1.9.1
 
+RUBY_EXEC_PREFIX = /opt/ruby-1.9.2-p0
+RUBY_LIB_PREFIX  = $(RUBY_EXEC_PREFIX)/lib/ruby
+RUBY_SITE_LIB = $(RUBY_LIB_PREFIX)/site_ruby
+RUBY_VENDOR_LIB = $(RUBY_LIB_PREFIX)/vendor_ruby
+RUBY_PLATFORM = x86_64-linux
+
 #### Start of system configuration section. ####
 
+prefix = $(RUBY_EXEC_PREFIX)
 srcdir = .
-topdir = /usr/lib/ruby/$(VER)/i486-linux
+topdir = $(prefix)/lib/ruby/$(VER)/$(RUBY_PLATFORM)
 hdrdir = $(topdir)
 VPATH = $(srcdir):$(topdir):$(hdrdir)
 exec_prefix = $(prefix)
@@ -25,7 +31,8 @@
 infodir = $(prefix)/share/info
 vendorlibdir = $(vendordir)/$(ruby_version)
 sysconfdir = $(DESTDIR)/etc
-libdir = $(exec_prefix)/lib
+#libdir = $(exec_prefix)/lib
+libdir = $(RUBY_EXEC_PREFIX)/lib
 sbindir = $(exec_prefix)/sbin
 rubylibdir = $(libdir)/ruby/$(ruby_version)
 docdir = $(datarootdir)/doc/$(PACKAGE)
@@ -49,7 +56,7 @@
 RUBY_EXTCONF_H = 
 CFLAGS   =  -fPIC -fno-strict-aliasing -g -w -O2 -fPIC $(cflags) 
 # CFLAGS   =  -fPIC -fno-strict-aliasing -g -fPIC $(cflags) 
-INCFLAGS = -I. -I$(topdir) -I$(hdrdir) -I$(srcdir) -I/usr/include/libxml2 -I/usr/include/ruby-1.9.1 -I/usr/include/ruby-1.9.1/ruby -I/usr/include/ruby-1.9.1/i486-linux 
+INCFLAGS = -I. -I$(topdir) -I$(hdrdir) -I$(srcdir) -I/usr/include/libxml2 -I$(RUBY_EXEC_PREFIX)/include/ruby-1.9.1 -I$(RUBY_EXEC_PREFIX)/include/ruby-1.9.1/ruby -I$(RUBY_EXEC_PREFIX)/include/ruby-1.9.1/$(RUBY_PLATFORM) 
 DEFS     = -D_FILE_OFFSET_BITS=64
 CPPFLAGS =   $(DEFS) $(cppflags)
 CXXFLAGS = $(CFLAGS) 
@@ -62,12 +69,11 @@
 EXEEXT = 
 
 RUBY_INSTALL_NAME = ruby$(VER)
-# RUBY_SO_NAME = ruby$(VER)
-RUBY_SO_NAME = ruby-$(VER)
-arch = i486-linux
-sitearch = i486-linux
+RUBY_SO_NAME = ruby
+arch = $(RUBY_PLATFORM)
+sitearch = $(RUBY_PLATFORM)
 ruby_version = $(VER)
-ruby = /usr/bin/ruby$(VER)
+ruby = $(RUBY_EXEC_PREFIX)/bin/ruby
 RUBY = $(ruby)
 RM = rm -f
 MAKEDIRS = mkdir -p
@@ -93,7 +99,31 @@
 LOCAL_LIBS = 
 LIBS = $(LIBRUBYARG_SHARED)  -lpthread -lrt -ldl -lcrypt -lm   -lc -lmemcached -lxml2
 SRCS = parse_doc.cpp write_metrics.cpp parallel.cpp main.cpp
+
+# XXX Fix this issue. Or my (BJA) understanding or Makefiles.
+#
+# We need to use two different lists of OBJS depending on whether we're
+# compiling or linking.  (Actually the linking set of OBJS works for compiling
+# as long as nothing in ../common has changed).
+#
+# The issue is that running `make` from the `meryl` directory results in
+# `utils.o` and `memcache.o` being compiled into `.` not `../common`.  The
+# linking task can then not find them.
+#
+# Remembering to swap this out really defeats the purpose of using Make.
+# Perhaps, I'm just running `make` from the wrong location.  Perhaps I should
+# be running `make` from `../common` in order to build the `utils.o` and
+# `memcache.o` objects.  But in that case, why does this Makefile compile them
+# into `.`?  Something is not quite right.  That could well be my understanding
+# of Makefiles.
+#
+# Use this list of objects to compile when anything in ../common has changed.
 OBJS = ../common/utils.o ../common/memcache.o parse_doc.o write_metrics.o parallel.o main.o
+#
+# Use this list of objects to compile when nothing in ../common has changed and
+# to link the object files into the shared object.
+#OBJS = utils.o memcache.o parse_doc.o write_metrics.o parallel.o main.o
+
 TARGET = MerylNumberCruncher
 DLLIB = $(TARGET).so
 EXTSTATIC = 
