- name: Install ct-visualiation-app tarball from s3
  vars:
    destination_dir: "{{ rails_root_dir }}"
    s3_prefix: "{{s3_appliances_prefix}}"
    tarball_name: ct-visualiation-app.tgz
    untarred_dir: ct-visualiation-app
    correct_owner: "{{app_user}}"
    correct_group: "{{app_user}}"
  include_tasks: install_s3_tarball.yml
