- name: Install dependencies
  register: result
  until: result is success
  ansible.builtin.apt:
    name:
      - ruby3.0

- name: Install build dependencies
  register: result
  until: result is success
  ansible.builtin.apt:
    name:
      - ruby3.0-dev
      - autoconf
      - bison
      - build-essential
      - libpq-dev

- name: Check for existing installation
  ansible.builtin.command:
    cmd: ls -d {{ ct_vis_app_path }}
  register: ct_vis_app_dir
  failed_when: False

- name: Install ct-visualisation-app
  include_tasks: install_ct_vis_app_package.yml
  when: ct_vis_app_dir.stdout == ""

- name: Install logrotate configuration
  ansible.builtin.template:
    src: ct-visualisation-app.logrotate
    dest: /etc/logrotate.d/ct-visualisation-app

- name: Bundle install gems
  register: result
  until: result is success
  ansible.builtin.shell: |
    cd "{{ ct_vis_app_path }}"
    ./bin/bundle install

- name: Generate shared secret
  include_tasks: generate_shared_secret.yml

- name: Create new master key and credentials
  block:
    - name: Remove existing key and credentials
      ansible.builtin.file:
        path: "{{ct_vis_app_path}}/config/{{item}}"
        state: absent
      loop:
        - master.key
        - credentials.yml.enc

    - name: Create master key and credentials
      ansible.builtin.shell:
        chdir: "{{ ct_vis_app_path }}"
        cmd: |
          sudo -u {{app_user}} /bin/bash -c 'EDITOR=cat ./bin/rails credentials:edit'

    - name: Generate encryption keys
      ansible.builtin.shell:
        chdir: "{{ ct_vis_app_core_dir }}"
        cmd: sudo -u {{app_user}} /bin/bash -c './bin/rake encryption:generate'

- name: Adjust database config with host and password
  vars:
   # db_password: "{{ lookup('ansible.builtin.file', '/run/secrets/db/password.txt') }}"
   db_password: db_password
  ansible.builtin.replace:
    path: "{{ct_installation_dir}}/ct-visualisation-app/config/database.yml"
    regexp: "{{item.regexp}}"
    replace: "{{item.replace}}"
  loop:
    - regexp: '^(\s*)#\s*host:.*$'
      replace: '\1host: {{db_host}}'
    - regexp: '^(\s*)#\s*password:.*$'
      replace: '\1password: {{db_password}}'
  when: docker_build | bool

- name: Setup database
  when: not docker_build | bool
  import_tasks: setup_database.yml

- name: Create default users
  when: not docker_build | bool
  import_tasks: create_default_users.yml

- name: Add licence limits
  import_tasks: licence_limits.yml

- name: Precompile assets
  import_tasks: run_rake_task.yml
  vars:
    ruby_bin_dir: "{{ruby_30_bin_dir}}"
    rake_task: "assets:precompile"
    additional_env: ""
    chdir: "{{ ct_vis_app_path }}"

- name: Install systemd service files
  ansible.builtin.template:
    src: "{{item}}.service"
    dest: /lib/systemd/system/{{item}}.service
    owner: root
    group: root
    mode: "644"
  loop:
    - ct-visualisation-app
    - ct-visualisation-job-runner

- name: Enable visualisation app (non-docker)
  ansible.builtin.service:
    name: "{{item}}"
    enabled: yes
    state: restarted
  loop:
    - ct-visualisation-app
    - ct-visualisation-job-runner
  when: not docker_build | bool

- name: Enable visualisation app (docker)
  ansible.builtin.file:
    src: /lib/systemd/system/{{item}}.service
    dest: /etc/systemd/system/multi-user.target.wants/{{item}}.service
    state: link
  loop:
    - ct-visualisation-app
    - ct-visualisation-job-runner
  when: docker_build | bool
