- name: Install monit
  register: result
  until: result is success
  ansible.builtin.apt:
    name: monit
    state: latest

# We will enable monit after MIA is configured.  Until then we don't
# necessarily expect all of the services to work correctly.
- name: Stop monit
  ansible.builtin.service:
    name: monit
    state: stopped
    enabled: no
  when: not docker_build | bool

- name: Install configuration
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"

  loop:
    - src: monit.default
      dest: /etc/default/monit
      owner: root
      group: root
      mode: "644"

    - src: monitrc
      dest: /etc/monit/monitrc
      owner: root
      group: root
      mode: "700"

- name: Install monitored services configuration
  ansible.builtin.copy:
    src: services/
    dest: /etc/monit/conf.d/
