- name: Add netplan config for eth0
  block:
    - name: Copy cloud init netplan
      ansible.builtin.copy:
        remote_src: true
        src: "{{ cloud_init_netplan }}"
        dest: "{{ eth0_netplan }}"

    - name: Remove comments
      ansible.builtin.lineinfile:
        regexp: '^#'
        state: absent
        path: "{{ eth0_netplan }}"

    - name: Set name to eth0
      ansible.builtin.lineinfile:
        regexp: '^(\s*)set-name:'
        line: '\1set-name: eth0'
        backrefs: true
        path: "{{ eth0_netplan }}"

- name: Disable cloud-init's network configuration capabilities
  block:
    - name: Remove generated cloud-init netplan config
      ansible.builtin.file:
        path: "{{ cloud_init_netplan }}"
        state: absent

    - name: Prevent re-generation of cloud-init netplan config
      ansible.builtin.copy:
        dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        content: |
          network: {config: disabled}
        owner: root
        group: root
        mode: "644"
