- name: Check for ethX naming
  ansible.builtin.command:
    cmd: ls -d /sys/class/net/eth0
  register: ethX_naming_check
  failed_when: False

- name: Enable ethX naming
  import_tasks: enable_ethX_naming.yml
  when: ethX_naming_check.stdout == ""

- name: Inform of need to reboot
  when: ethX_naming_check.stdout == ""
  ansible.builtin.debug:
    msg:
      - "ethX naming for network interfaces has been enabled."
      - "The machine must be rebooted for this to take affect."
      - "The build and configure playbooks should not be ran until after the machine is rebooted."

- name: Inform OK to continue
  when: ethX_naming_check.stdout != ""
  ansible.builtin.debug:
    msg:
      - "ethX naming for network interfaces was already enabled."
      - "The build and configure playbooks should now be ran."
