- name: Extract tar file
  ansible.builtin.unarchive:
    src: "{{ item }}.tgz"
    dest: /
    creates: /opt/{{ item }}
  loop:
    - openssl-1.0.2u
    - openssl-1.0.2l
    - ruby-1.8.7-p374
    - ruby-1.9.2-p0

- name: Link Rubies
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: /opt/ruby-1.8.7-p374
      dest: /opt/ruby-1.8.7

    - src: /opt/ruby-1.8.7
      dest: /opt/ruby-1.8

    - src: /opt/ruby-1.9.2-p0
      dest: /opt/ruby-1.9.2

    - src: /opt/ruby-1.9.2
      dest: /opt/ruby-1.9

- name: Link Ruby binaries
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: /opt/ruby-1.8/bin/ruby
      dest: /usr/bin/ruby1.8

    - src: /opt/ruby-1.8/bin/gem
      dest: /usr/bin/gem1.8

    - src: /opt/ruby-1.8/bin/irb
      dest: /usr/bin/irb1.8

    - src: /opt/ruby-1.9/bin/ruby
      dest: /usr/bin/ruby1.9

    - src: /opt/ruby-1.9/bin/gem
      dest: /usr/bin/gem1.9

    - src: /opt/ruby-1.9/bin/irb
      dest: /usr/bin/irb1.9

    - src: /opt/ruby-1.9/bin/rake
      dest: /usr/bin/rake1.9
