- name: Install Ruby and OpenSSL packages
  vars:
    download_dest: "{{ role_path }}/files/tmp/{{ item }}.tgz"
  block:
    - name: Download packages from S3
      amazon.aws.aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ s3_misc_packages_prefix }}{{ item }}.tgz"
        dest: "{{ download_dest }}"
        mode: get
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
      loop: "{{ ruby_build_assets }}"
    
    - name: Extract tar file
      ansible.builtin.unarchive:
        src: "{{ download_dest }}"
        dest: /
        creates: /opt/{{ item }}
      loop: "{{ ruby_build_assets }}"

- name: Link Rubies
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: /opt/ruby-1.8.7-p374
      dest: /opt/ruby-1.8.7

    - src: /opt/ruby-1.8.7
      dest: /opt/ruby-1.8

    - src: /opt/ruby-1.9.2-p0
      dest: /opt/ruby-1.9.2

    - src: /opt/ruby-1.9.2
      dest: /opt/ruby-1.9

- name: Link Ruby binaries
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ruby_18_bin_dir}}ruby"
      dest: /usr/bin/ruby1.8

    - src: "{{ruby_18_bin_dir}}/gem"
      dest: /usr/bin/gem1.8

    - src: "{{ruby_18_bin_dir}}/irb"
      dest: /usr/bin/irb1.8

    - src: "{{ruby_19_bin_dir}}/ruby"
      dest: /usr/bin/ruby1.9

    - src: "{{ruby_19_bin_dir}}/gem"
      dest: /usr/bin/gem1.9

    - src: "{{ruby_19_bin_dir}}/irb"
      dest: /usr/bin/irb1.9

    - src: "{{ruby_19_bin_dir}}/rake"
      dest: /usr/bin/rake1.9

    - src: /usr/bin/ruby1.9
      dest: /usr/bin/ruby1.9.1
