- name: Copy config
  ansible.builtin.copy:
    src: "{{ daemon_installation_dir}}/ailsa/config/config.yml.mia.template"
    remote_src: true
    dest: "{{ daemon_installation_dir}}/ailsa/config/config.yml"
