# XXX Port these to git repo.
- name: Patch ct-capacity-daemon source code
  vars:
    daemon: ct-capacity-daemon
  ansible.builtin.patch:
    src: "patches/{{ item }}"
    basedir: "{{ daemon_installation_dir }}/{{ daemon }}"
    backup: yes
    strip: 1
  loop:
    - ct-capacity-daemon-hack-around-lack-of-eth1.patch

