- name: Download daemon packages from S3
  amazon.aws.aws_s3:
    bucket: "{{s3_bucket}}"
    object: "{{s3_daemons_prefix}}{{ item }}.tgz"
    dest: "{{ role_path }}/files/tmp/{{ item }}.tgz"
    mode: get
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  loop: "{{ packaged_daemons }}"

- name: Make destination directory
  ansible.builtin.file:
    path: "{{ daemon_installation_dir }}"
    owner: root
    group: root
    mode: "755"
    state: directory

- name: Extract tar files
  ansible.builtin.unarchive:
    src: "tmp/{{ item }}.tgz"
    dest: "{{ daemon_installation_dir }}"
    creates: "{{ daemon_installation_dir }}/{{ item }}"
  loop: "{{ packaged_daemons }}"

- name: Install number crunchers
  block:
    - name: Download number cruncher from S3
      amazon.aws.aws_s3:
        bucket: "{{s3_bucket}}"
        object: "{{s3_daemons_prefix}}{{ item }}-number-cruncher.deb"
        dest: "{{ role_path }}/files/tmp/{{ item }}-number-cruncher.deb"
        mode: get
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
      loop: "{{ number_crunchers }}"

    - name: Install number cruncher deb package
      ansible.builtin.apt:
        deb: "{{ role_path }}/files/tmp/{{ item }}-number-cruncher.deb"
      loop: "{{ number_crunchers }}"

- name: Patch bundler source
  vars:
    gemfile: "{{daemon_installation_dir}}/{{item}}/Gemfile"
    original_source: ":gemcutter"
  include_tasks: patch_bundler_source.yml
  loop: "{{packaged_daemons}}"

- name: Additional ailsa configuration
  include_tasks: ailsa_config.yml

- name: Install gem dependencies
  vars:
    daemon_path: "{{ daemon_installation_dir}}/{{ item }}"
  ansible.builtin.shell: |
    cd "{{ daemon_path }}"
    PATH={{ruby_19_bin_dir}}:$PATH
    {{ruby_19_bin_dir}}/bundle install
  loop: "{{ packaged_daemons }}"

- name: Install init.d files
  ansible.builtin.copy:
    src: "{{ item }}.init"
    dest: /etc/init.d/{{ item }}
    owner: root
    group: root
    mode: "744"
  loop: "{{ packaged_daemons + init_only_daemons }}"
  # XXX deal with UID check.

# - name: Additional demm configuration
#   vars:
#     limits_dir: "{{ct_etc_dir}}/appliance/limits"
#     demm_path: "{{ daemon_installation_dir }}/demm"
#   block:
#     - name: Make limits directory
#       ansible.builtin.file:
#         path: "{{ limits_dir }}"
#         state: directory
#         owner: www-data
#         group: root
#         mode: "755"

#     - name: Copy demm limits
#       ansible.builtin.copy:
#         src: "{{ demm_path }}/config/demm.yml.limits"
#         remote_src: true
#         dest: "{{ limits_dir }}/demm.yml"
#         owner: www-data
#         group: root
#         mode: "644"

- name: Install clobber script
  ansible.builtin.copy:
    src: scripts/clobber
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: "755"

# - name: Install hw.sh script


- name: Ensure that daemons are enabled
  ansible.builtin.service:
    name: "{{ item }}"
    # state: started
    enabled: yes
  loop: "{{ packaged_daemons + init_only_daemons }}"
