# Not entirely decided on the correct naming for the daemon.  Should all new
# daemons be prefixed with ct-?
- name: Fix issue with metric-reporting-daemon name
  ansible.builtin.file:
    src: "{{daemon_installation_dir}}/metric-reporting-daemon"
    dest: "{{daemon_installation_dir}}/ct-metric-reporting-daemon"
    state: link

- name: Generate shared secret
  vars:
    secret_file: "{{ daemon_installation_dir }}/ct-metric-reporting-daemon/config/secret"
  block:
    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{item}}"
        owner: root
        group: "{{app_user}}"
        mode: "755"
        state: directory
      loop:
        - "{{ daemon_installation_dir }}/ct-metric-reporting-daemon"
        - "{{ daemon_installation_dir }}/ct-metric-reporting-daemon/config"

    - name: Created secret
      ansible.builtin.shell:
        cmd: |
          PATH={{ruby_19_bin_dir}}:$PATH
          ruby -r securerandom -e 'puts SecureRandom.hex(64)' > {{secret_file}}

    - name: Ensure {{app_user}} can read file
      ansible.builtin.file:
        path: "{{secret_file}}"
        owner: root
        group: "{{app_user}}"
        mode: "640"
