- name: Install release.info from s3
  vars:
    dest: "{{ release_info_dest }}"
    file: release.info
    s3_prefix: "{{s3_packages_prefix}}"
    correct_owner: "{{app_user}}"
    correct_group: "{{app_user}}"
    correct_mode: "644"
  include_tasks: install_s3_file.yml

- name: Install version.yml from s3
  vars:
    dest: "{{ version_yml_dest }}"
    file: version.yml
    s3_prefix: "{{s3_packages_prefix}}"
    correct_owner: "{{app_user}}"
    correct_group: "{{app_user}}"
    correct_mode: "644"
  include_tasks: install_s3_file.yml

- name: Append version.yml to release.yml
  ansible.builtin.shell:
    cmd: |
      cat {{ version_yml_dest }} >> {{ release_yml_dest }}

# - name: Install license creation script
# XXX Replace below with above creation script.
- name: Install fake licenses
  ansible.builtin.copy:
    content: |
      {}
    dest: "{{ licenses_yml_dest }}"
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: "644"
