- name: Add release.info
  ansible.builtin.copy:
    src: release.info
    dest: "{{ release_info_dest }}"
    owner: www-data
    group: www-data
    mode: "644"

- name: Add version.yml
  ansible.builtin.copy:
    src: version.yml
    dest: "{{ version_yml_dest }}"
    owner: www-data
    group: www-data
    mode: "644"

- name: Append version.yml to release.yml
  ansible.builtin.shell:
    cmd: |
      cat {{ version_yml_dest }} >> {{ release_yml_dest }}

# - name: Install license creation script
# XXX Replace below with above creation script.
- name: Install fake licenses
  ansible.builtin.copy:
    content: |
      {}
    dest: "{{ licenses_yml_dest }}"
    owner: www-data
    group: www-data
    mode: "644"
