- name: Install required packages
  ansible.builtin.apt:
    name: 
      - awscli
      - golang

- name: Remove prior builds
  ansible.builtin.file:
    path: "{{ package_assets_package_dir }}"
    state: absent
  when: remove_prior_builds == True

- name: Create build and package directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "755"
    state: directory
  loop:
    - "{{ package_assets_package_dir }}"
    - "{{ package_assets_repo_dir }}"

- name: Build ruby packages
  include_tasks: build-ruby-package.yml
  tags: ruby-packages
  loop: "{{package_assets_ruby_projects}}"

- name: Build golang packages
  include_tasks: "build-golang-package.yml"
  tags: golang-packages
  loop: "{{package_assets_golang_projects}}"

- name: Build fake gmond package
  import_tasks: build-fake-gmond-package.yml
  tags: fake-gmond

- name: Upload packages
  import_tasks: upload-packages.yml
  tags: upload
