CT_SRC_DIR = [ ENV['FLIGHT_CODE'], "#{ENV['HOME']}/projects/concertim/src" ]
  .compact
  .map { |p| File.expand_path(p) }
  .detect { |p| File.directory?(p) }
ANSIBLE_DIR="../ansible"
MACHINES = [
  {
    name: "dev1",
    box: "ubuntu/jammy64",
  },
  {
    name: "dev2",
    box: "ubuntu/jammy64",
  },
  {
    name: "asset-build",
    box: "ubuntu/jammy64",
  }
]

Vagrant.configure("2") do |config|
  MACHINES.each_with_index do |box, idx|
    config.vm.provider "virtualbox" do |v|
      # v.memory = 8192
      # v.memory = 4096
      # v.memory = 3072
      v.memory = 2048
    end

    config.vm.define box[:name], primary: idx == 0 do |v|
      v.vm.box = box[:box]
      v.vm.hostname = "concertim-#{box[:name]}"
      v.vm.provider "virtualbox" do |p|
        # This needs to be nested inside the `config.vm.define` block to set
        # the name for just this box.
        p.name = "concertim_#{box[:name]}_#{Time.now.to_f.to_s.sub('.', '_')}"
      end

      # Forward HTTP/S ports at predictable host ports.  Redirection from HTTP
      # to HTTPS isn't expected to work with these ports.
      v.vm.network "forwarded_port", guest:  80, host: 9080 + idx + 1, host_ip: '127.0.0.1'
      v.vm.network "forwarded_port", guest: 443, host: 9443 + idx + 1, host_ip: '127.0.0.1'

      v.vm.provision "swap",
        type: "shell",
        path: "scripts/create-swap.sh",
        run: "never"
      v.vm.provision "apt-upgrade",
        type: "shell",
        inline: "apt-get -y update && apt-get -y upgrade",
        run: "never"

      unless to_boolean(ENV['ACCEPTANCE'])
        v.vm.synced_folder ANSIBLE_DIR, "/ansible"
        if File.directory?(CT_SRC_DIR)
          v.vm.synced_folder CT_SRC_DIR, "/data/private/share/dev"
        end

        if Vagrant.has_plugin?("vagrant-notify-forwarder")
          # Notify forwarder forwards notifications for file system changes.
          # This enables quick dev reloading in rails apps and air.
          v.notify_forwarder.port = 22021
        else
          $stderr.puts <<~EOF
          WARNING: vagrant-notify-forwarder is not installed.

          Run the following for a much better development experience.

          vagrant plugin install vagrant-notify-forwarder

          EOF
        end

        # Build the VM in the same was as the ansible README instructions
        # state.  These are only available when `ACCEPTANCE` has not been defined.
        v.vm.provision "install_ansible",
          type: "shell",
          run: "never",
          path: "scripts/install-ansible.sh"
        v.vm.provision "run_build_playbook",
          type: "shell",
          run: "never",
          inline: <<-SH
            AWS_ACCESS_KEY_ID=#{ENV.fetch('AWS_ACCESS_KEY_ID', '')} AWS_SECRET_ACCESS_KEY=#{ENV.fetch('AWS_SECRET_ACCESS_KEY', '')} /vagrant/scripts/run-build-playbook.sh
          SH

      end
    end
  end
end

def to_boolean(v)
  case v
  when /true/i, /yes/i, "1"
    true
  else
    false
  end
end
