ANSIBLE_DIR="../ansible"
BOXES = [
  {
    name: "command1",
    box: "bento/ubuntu-22.04",
    acceptance: false,
  },
  {
    name: "command2",
    box: "ubuntu/focal64",
    acceptance: false,
  }
]

Vagrant.configure("2") do |config|
  BOXES.each_with_index do |box, idx|
    config.vm.provider "virtualbox" do |v|
      # v.memory = 8192
      v.memory = 2048
    end

    config.vm.define box[:name], primary: idx == 0 do |v|
      v.vm.box = box[:box]
      v.vm.hostname = box[:name]
      v.vm.network "forwarded_port", guest:  80, host: 9080 + idx, host_ip: '127.0.0.1'
      v.vm.network "forwarded_port", guest: 443, host: 9443 + idx, host_ip: '127.0.0.1'

      unless box[:acceptance]
        v.vm.provision "ansible_local" do |ansible|
          ansible.playbook = File.join(ANSIBLE_DIR, "build-playbook.yml")
          ansible.verbose = to_boolean(ENV.fetch('ANSIBLE_VERBOSE', 'false'))

          ansible.extra_vars = {
            'github_token' => ENV.fetch('GH_TOKEN', ''),
            'aws_access_key_id' => ENV.fetch('AWS_ACCESS_KEY_ID', ''),
            'aws_secret_access_key' => ENV.fetch('AWS_SECRET_ACCESS_KEY', ''),
          }
        end

        v.vm.synced_folder ANSIBLE_DIR, "/ansible"
      end
    end
  end
end

def to_boolean(v)
  case v
  when /true/i, /yes/i, "1"
    true
  else
    false
  end
end
