# ==================================================
# Components to install
# ==================================================

# Select which components you wish to install and enable.

# If the concertim component is enabled, the visualisation,
# metric_reporting_daemon, proxy and db containers will be installed and
# enabled.
enable_concertim: yes

# If the cluster builder component is enabled, the cluster builder container
# will be installed and enabled.
enable_cluster_builder: yes

# If the openstack service component is enabled, the api_server, bulk_updates,
# mq_listener and metrics concertim openstack service containers will be
# installed and enabled.
enable_openstack_service: yes

# If the killbill component is enabled, the killbill, kaui and killbill_db
# components will be installed and enabled.
enable_killbill: yes

# ==================================================
# Host Ports and Interfaces
# ==================================================

# The port that the proxy service should listen to HTTPS requests on.
proxy_https_port: 7443
# The interface that the proxy service should listen to HTTPS requests on.
# Use 0.0.0.0 to listen on all interfaces.
proxy_https_interface: 0.0.0.0

# The port that the proxy service should listen to HTTP requests on.
# Listening for HTTP requests is optional.
# All requests received on this port are forwarded to `proxy_https_port`.
# Set to false disable listening for HTTP requests.
proxy_http_port: 7080
# The interface that the proxy service should listen to HTTP requests on.
# Use 0.0.0.0 to listen on all interfaces.
# If `proxy_http_port` is `false`, this setting is ignored.
proxy_http_interface: 0.0.0.0

# The port that the metric reporting daemon service should listen to HTTP requests on.
metric_reporting_daemon_api_port: 43000
# The interface that the proxy service should listen to HTTPS requests on.
# Use 0.0.0.0 to listen on all interfaces.
metric_reporting_daemon_api_interface: 127.0.0.1

# The port that the visualisation app service should listen to HTTP requests on.
visualisation_app_port: 7000
# The interface that the proxy service should listen to HTTPS requests on.
# Use 0.0.0.0 to listen on all interfaces.
visualisation_app_interface: 127.0.0.1

# The port that the cluster builder service should listen to HTTP requests on.
cluster_builder_port: 42378
# The interface that the cluster builder service should listen to HTTP requests on.
# Use 0.0.0.0 to listen on all interfaces.
cluster_builder_interface: 127.0.0.1

# The port that the db service should listen on.
db_port: 45432
# The interface that the db service should listen on.
# Use 0.0.0.0 to listen on all interfaces.
db_interface: 127.0.0.1

# The interface that the concertim openstack api server service should
# listen to HTTP requests on.
# Use 0.0.0.0 to listen on all interfaces.
api_server_interface: 127.0.0.1

# The port that the killbill service should listen on.
killbill_port: 48080
# The interface that the killbill service should listen on.
# Use 0.0.0.0 to listen on all interfaces.
killbill_interface: 0.0.0.0

# The port that the killbill service should listen on.
kaui_port: 49090
# The interface that the killbill service should listen on.
# Use 0.0.0.0 to listen on all interfaces.
kaui_interface: 0.0.0.0
