package_assets_ruby_projects:
  - repo: concertim-ct-visualisation-app
    name: ct-visualisation-app
    # This could be a git tag, git branch or git commit.
    tag: refactor/engines
    type: appliance
    subdir: ""

package_assets_golang_projects:
  - repo: concertim-metric-reporting-daemon
    name: ct-metric-reporting-daemon
    # This could be a git tag, git branch or git commit.
    tag: main
    type: daemon
    subdir: ""
