- name: Run main generatortron
  import_tasks: generatortron.yml
  vars:
    description: main
    rails_env: production
    rails_runner: ./script/rails runner
    script_path: "{{ role_path }}/files/scripts/generatortron.rb"
    data_path: "{{ role_path }}/files/data.yaml"
    ruby_bin: /opt/ruby-1.9/bin
    chdir: /data/private/share/rails/emma/core

- name: Run meca generatortron
  import_tasks: generatortron.yml
  vars:
    description: meca
    rails_env: production
    rails_runner: ./script/runner
    script_path: "{{ role_path }}/files/scripts/generatortron_meca.rb"
    data_path: "{{ role_path }}/files/data.yaml"
    ruby_bin: /opt/ruby-1.8/bin
    chdir: /data/private/share/rails/meca

- name: Restart meryl
  ansible.builtin.service:
    name: meryl
    state: restarted

- name: Ensure fake gmond is running
  ansible.builtin.service:
    name: fake-ganglia
    state: started
