- name: Run main generatortron
  import_tasks: generatortron.yml
  vars:
    description: main
    additional_env: ""
    rails_runner: ./script/rails runner
    script_path: "{{ role_path }}/files/scripts/generatortron.rb"
    data_path: "{{ role_path }}/files/data.yaml"
    ruby_bin_dir: "{{ruby_19_bin_dir}}"
    chdir: /data/private/share/rails/emma/core

- name: Stop meca
  ansible.builtin.service:
    name: phoenix-mongrel@meca.3003.service
    state: stopped

- name: Run meca generatortron
  import_tasks: generatortron.yml
  vars:
    description: meca
    # additional_env: "PHOENIX_START=false"
    additional_env: ""
    rails_runner: ./script/runner
    script_path: "{{ role_path }}/files/scripts/generatortron_meca.rb"
    data_path: "{{ role_path }}/files/data.yaml"
    ruby_bin_dir: "{{ruby_18_bin_dir}}"
    chdir: /data/private/share/rails/meca

- name: Start meca
  ansible.builtin.service:
    name: phoenix-mongrel@meca.3003.service
    state: started

- name: Restart meryl
  ansible.builtin.service:
    name: meryl
    state: restarted

- name: Ensure fake gmond is running
  ansible.builtin.service:
    name: fake-ganglia
    state: started
