# Allow all local users trusted access to the database.  This allows the
# `vagrant` user to access the database as {{app_user}}.  This is very useful
# for dealing with file permissions for the vagrant vboxfs.

- name: Trusted access to database for all local users
  ansible.builtin.replace:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: "local *all *all *peer"
    replace: "local   all             all                                     trust"
    backup: true

- name: Restart postgresql
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes
