# Install tools that are for development.  Tools that are useful
# for production debugging and maintenance should be installed by the
# misc-packages role.
- name: Install useful dev tools
  ansible.builtin.apt:
    name: []
    state: latest

# As above, install scripts that are for development.  Scripts that are useful
# for production debugging and maintenance should be installed by the
# misc-packages role.
- name: Install useful dev scripts
  ansible.builtin.copy:
    src: scripts/
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: "0755"

- name: Nginx dev configuration
  include_tasks: nginx_dev_configuration.yml

- name: Configure trusted access to database
  include_tasks: database_trusted_access.yml

- name: Setup dev ct-visualisation-app
  include_tasks: setup_dev_ct_vis_app.yml
