# FSR the non-dev version of requirejs isn't installed.  It is present on the
# `safe-persistent deploy` built MIA, but not this ansible built one.  Don't
# yet know why.
- name: Use dev requirejs
  ansible.builtin.replace:
    path: "{{ item[0] }}"
    regexp: "{{ item[1].regexp }}"
    replace: "{{ item[1].replace }}"
    backup: true
  with_nested:
    - "{{ requirejs_boot_files }}"
    - "{{ replacements }}"
  vars:
    requirejs_boot_files:
      - "{{rails_root_dir}}/mia/app/views/layouts/mia.rhtml"
      - "{{rails_root_dir}}/emma/core/app/views/layouts/application.html.erb"
    replacements:
      - regexp: '<script data-main="/scripts/lib/main" src="/scripts/lib/contrib/require.js"></script>'
        replace: '<%#<script data-main="/scripts/lib/main" src="/scripts/lib/contrib/require.js"></script>%>'
      - regexp: '<%#<script data-main="/scripts/src/meta/dev" src="/scripts/src/javascript/contrib/require.js"></script>%>' 
        replace: => '<script data-main="/scripts/src/meta/dev" src="/scripts/src/javascript/contrib/require.js"></script>'
