- name: Check for dev installation
  ansible.builtin.command:
    cmd: ls -d {{dev_root_dir}}/ct-visualisation-app
  register: dev_ct_vis_dir
  failed_when: False


- name: Bundle install gems for dev ct-visualisation-app
  ansible.builtin.shell: |
    cd {{dev_root_dir}}/ct-visualisation-app/core
    ./bin/bundle install
  when: dev_ct_vis_dir.stdout != ""


- name: Disable production ct-visualisation-app
  ansible.builtin.service:
    name: "{{item}}"
    state: stopped
    enabled: no
  loop:
    - ct-visualisation-app
    - ct-visualisation-job-runner
