- name: Workaround git and vboxfs issue
  ansible.builtin.command:
    cmd: git config --global --add safe.directory /opt/concertim/dev/ct-metric-reporting-daemon


- name: Build metric reporting daemon server
  ansible.builtin.command:
    cmd: go build -o ./tmp/reporting ./cmd/reporting/
    chdir: "{{dev_root_dir}}/ct-metric-reporting-daemon"


- name: unmonitor metric daemons
  ansible.builtin.command:
    cmd: monit unmonitor -g ct-metrics


- name: Disable production metric daemons
  ansible.builtin.service:
    name: "{{item}}"
    state: stopped
    enabled: no
  loop:
    - ct-metric-reporting-daemon


- name: Start dev servers
  ansible.builtin.command:
    cmd: screen -dmS {{item.name}} ./tmp/{{item.exe}}
    chdir: "{{dev_root_dir}}/ct-metric-reporting-daemon"
  loop:
    - exe: reporting
      name: ct-metrics
