- name: Workaround git and vboxfs issue
  ansible.builtin.command:
    cmd: git config --global --add safe.directory /opt/concertim/dev/ct-metric-reporting-daemon

- name: Build metric reporting daemon server
  register: result
  until: result is success
  ansible.builtin.command:
    cmd: go build -o ./tmp/reporting ./cmd/reporting/
    chdir: "{{dev_root_dir}}/ct-metric-reporting-daemon"

- name: unmonitor metric daemons
  ansible.builtin.command:
    cmd: monit unmonitor -g ct-metrics

- name: Disable production metric daemon
  ansible.builtin.service:
    name: "{{item}}"
    state: stopped
    enabled: no
  loop:
    - ct-metric-reporting-daemon

- name: Install air
  ansible.builtin.shell:
    cmd: |
      curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

- name: Start dev metric daemon
  ansible.builtin.shell:
    cmd: screen -dmS ct-metrics $(go env GOPATH)/bin/air -- --config-file config/config.dev.vm.yml
    chdir: "{{dev_root_dir}}/ct-metric-reporting-daemon"
