version: "3.3"
services:
  concertim:
    build:
      context: .
      dockerfile: docker/visualisation/Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    secrets:
      - db-password
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - static-content:/opt/concertim/opt/ct-visualisation-app/core/public
      - concertim-etc:/opt/concertim/etc
    expose:
      - 7000
    depends_on:
      - db

  metrics:
    build:
      context: .
      dockerfile: docker/metrics/Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - concertim-etc:/opt/concertim/etc
      - rrd-data:/var/lib/ganglia/rrds
    expose:
      - 3000

  proxy:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    ports:
      - 127.0.0.1:9080:80
      - 127.0.0.1:9443:443
    volumes:
      - static-content:/opt/concertim/opt/ct-visualisation-app/core/public
    depends_on:
      - concertim
      - metrics

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  rrd-data:
  static-content:
  concertim-etc:

secrets:
  db-password:
    file: docker/secrets/db/password.txt
