- name: Install 1.8 gems
  ansible.builtin.command:
    cmd: gem1.8 install "{{ role_path }}/files/1.8/{{ item }}*.gem" --no-rdoc --no-ri --local
  loop:
    - delia_daemon
    - delia-1.0.0

- name: Install 1.9 gems
  ansible.builtin.command:
    cmd: gem1.9 install "{{ role_path }}/files/1.9/{{ item }}*.gem" --no-rdoc --no-ri --local
  loop:
    - delia_daemon

- name: Link binaries
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{gem_18_bin_dir}}/delia"
      dest: /usr/bin/delia
    - src: "{{gem_18_bin_dir}}/check-delia"
      dest: /usr/bin/check-delia

- name: Install delia configuration
  ansible.builtin.copy:
    src: delia.yml
    dest: /data/private/share/etc/concurrent-thinking/
    owner: "{{app_user}}"
    group: "{{app_user}}"
    mode: u=rw,g=r,o=r

- name: Install delia client configuration
  ansible.builtin.copy:
    src: delia_client.yml
    dest: /data/public/resources/etc/concurrent-thinking/
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Install init.d file
  ansible.builtin.copy:
    src: delia.init
    dest: /etc/init.d/delia
    owner: root
    group: root
    mode: "744"

# XXX This ought to be elsewhere.
- name: Add sudoers entry
  ansible.builtin.lineinfile:
    line: "{{app_user}} ALL=NOPASSWD: ALL"
    path: "/etc/sudoers"
    insertbefore: EOF

- name: Ensure that delia is enabled
  ansible.builtin.service:
    name: delia
    enabled: yes
