- name: Configure gem source
  block:
    - name: Add local gem server
      ansible.builtin.command:
        cmd: "gem1.9 sources --add {{ gems_source }}"

    - name: Remove rubygems gem server
      ansible.builtin.command:
        cmd: "gem1.9 sources --remove http://rubygems.org/"

- name: Install bundler for ruby 1.9
  ansible.builtin.command:
    cmd: gem1.9 install --no-rdoc --no-ri bundler

- name: Create bundler1.9 symlink
  ansible.builtin.file:
    src: "{{ruby_19_bin_dir}}/bundle"
    dest: /usr/bin/bundle1.9
    state: link
