- name: Install Ruby 1.8 gem build depedencies
  ansible.builtin.apt:
    name:
      - librrd-dev
      - libpq-dev
      # - libgpgme11
      # - libgpgme-dev
      - libsnmp-dev
      - postgresql-server-dev-12
      - nodejs

# There are some hoops to jump through to get the Ruby 1.8 gems installed.
#
# Ideally we would simply `gem install <gem>` and have rubygems download the
# correct version and dependencies.  Unfortunately, this doesn't work for
# many (all?) of our gems.  The dependencies (or transitive dependencies)
# are resolved to recent versions that are not compatible with Ruby 1.8.
#
# Instead we need to install from the cached gem versions included in this
# repo.  Ideally, that would be as simple as `gem install *.gem --local` and
# rubygemns would resolve the dependencies from the cached version included
# in this repo.  Unfortunately, rubygems seems unable to do that.
#
# What we need to do is find an installation order in which all dependencies
# are installed before their dependent packages.  The order below is one
# such ordering: DO NOT change it.
- name: Install ruby 1.8 gems
  ansible.builtin.command:
    cmd: gem1.8 install "{{ role_path }}/files/1.8/{{ item }}*.gem" --no-rdoc --no-ri --local
  loop:
    - json_pure
    - rubyforge
    - rake
    - hoe
    - activesupport
    - activerecord-2.0.2  # Include version to increase specificity of the glob.
    - actionpack
    - actionmailer
    - activeresource
    - rails
    - netaddr
    - RubyRRDtool
    - roxml
    - sqlite3-ruby
    - gruff
    # - ferret
    - date_time-duration
    - phoenix-actionwebservice
    - postgres
    - libxml-ruby
    - archive-tar-minitar
    - highline
    - slave
    # - gpgme
    - deprecated
    - dbi
    - pg
    - dbd-pg
    - bundler
    - nokogiri
    - memcache-client
    - sequel
    - eventmachine
    - snmp
    - net-snmp
    - rack

    - beanstalk-client-free
    - phoenix_utils
    - data_source_core
    - romance-1.1.0  # Include version to increase specificity of the glob.
    - delia_client
    - activerecord-rdbcp-adapter
    - phoenix_validations
    - phoenix_metrics
    - phoenix_snmp
    - phoenix_update_signaller

- name: Install ruby 1.9 gems
  ansible.builtin.command:
    cmd: gem1.9 install "{{ role_path }}/files/1.9/{{ item }}*.gem" --no-rdoc --no-ri --local
  loop:
    - bundler
    - beanstalk-client-free
    - phoenix_utils
    - data_source_core
    - romance-1.2.0  # Include version to increase specificity of the glob.
    - delia_client
    - phoenix_update_signaller
    - phoenix_snmp
    - mini_magick_pgc
    - net-snmp
    # - ct_modbus

    # # These are required by emma, but not included in its vendor/cache FSR.
    # - data_source_core
    # - gem_plugin
    # - safe_core
    # - safe_libs
    # - safe_api
    # - RubyRRDtool

- name: Create bundler1.9 symlink
  ansible.builtin.file:
    src: /opt/ruby-1.9/bin/bundle
    dest: /usr/bin/bundle1.9
    state: link

- name: Install delia client config
  ansible.builtin.copy:
    src: delia_client.yml
    dest: /data/private/share/etc/concurrent-thinking/

