# Originally the "final" bundle installed a script which set the following
# when the MIA was rebooted.  We now do this as part of the configure process,
# which is somewhat earlier.  If we run into issues to do with these
# values this might be the case.
#
# I believe that this change is safe, as long was we only configure an
# appliance via the ansible configure playbook.  That is, as long as we no
# longer use the old "insert USB stick" method.
#
# XXX Is there a better way of doing this.  The loop and registering is quite
# unclear.
- name: Add asset limits
  vars:
    entries:
      - name: rack_limit
        default: 3
      - name: device_limit
        default: 100
      - name: nrad_limit
        default: 3
      - name: sensor_limit
        default: 5
      - name: vm_limit
        default: 5
      - name: cable_limit
        default: 10
      - name: asset_flag
        default: true
      - name: expire_time
        default: "{{ ansible_date_time.epoch + license_expires_in }}"
  block:
    - name: Check for existing entry
      ansible.builtin.shell:
        cmd: |
          grep -c "^{{ item.name }}:" "{{ release_yml_dest }}"
      register: existing_entry_test
      failed_when: False
      loop: "{{ entries }}"

    - name: Add asset limit entry
      ansible.builtin.lineinfile:
        path: "{{ release_yml_dest }}"
        line: "{{ item.item.name }}: {{ item.item.default }}"
        insertbefore: EOF
      loop: "{{ existing_entry_test.results }}"
      when: item.rc != 0

