sensors: []
non_rack_devices: []

racks:
  - name: Rack-1
    u_height: 42
    template_id: 669
    devices: []
    zero_u_devices: []

data_centre:
  image_path: /ansible/roles/demo-data/files/data_center_background.png
  x_dim: 4
  y_dim: 4

  rack_positions:
    - x_pos: 1.32
      y_pos: 1.42
      x_dim: 0.68
      y_dim: 1.18


  sensor_positions: []

power_cost_bands: []
groups: []
inferred_metrics: []
