sensors:
  - name: temp01
    template_id: 678
    sensor_type: temperature

  - name: temp02
    template_id: 678
    sensor_type: temperature

  - name: hum01
    template_id: 678
    sensor_type: humidity

  - name: hum02
    template_id: 678
    sensor_type: humidity

# XXX Add non-rack non-sensor devices.
non_rack_devices: []

racks:
  - name: Rack-1
    u_height: 42
    template_id: 669

    devices:
      - name: switch01
        template_id: 558
        type: Switch
        start_u: 41
        facing: "b"

      - name: comp029
        template_id: 613
        type: Server
        start_u: 39
        facing: "f"

      - name: comp028
        template_id: 613
        type: Server
        start_u: 38
        facing: "f"

      - name: comp027
        template_id: 613
        type: Server
        start_u: 37
        facing: "f"

      - name: comp026
        template_id: 613
        type: Server
        start_u: 36
        facing: "f"

      - name: comp025
        template_id: 613
        type: Server
        start_u: 35
        facing: "f"

      - name: comp024
        template_id: 613
        type: Server
        start_u: 34
        facing: "f"

      - name: comp023
        template_id: 613
        type: Server
        start_u: 33
        facing: "f"

      - name: comp022
        template_id: 613
        type: Server
        start_u: 32
        facing: "f"

      - name: comp021
        template_id: 613
        type: Server
        start_u: 31
        facing: "f"

      - name: comp020
        template_id: 613
        type: Server
        start_u: 30
        facing: "f"

      - name: comp019
        template_id: 613
        type: Server
        start_u: 29
        facing: "f"

      - name: comp018
        template_id: 613
        type: Server
        start_u: 28
        facing: "f"

      - name: comp017
        template_id: 613
        type: Server
        start_u: 27
        facing: "f"

      - name: comp016
        template_id: 613
        type: Server
        start_u: 26
        facing: "f"

      - name: comp015
        template_id: 613
        type: Server
        start_u: 25
        facing: "f"

      - name: comp014
        template_id: 613
        type: Server
        start_u: 24
        facing: "f"

      - name: comp013
        template_id: 613
        type: Server
        start_u: 23
        facing: "f"

      - name: comp012
        template_id: 613
        type: Server
        start_u: 22
        facing: "f"

      - name: comp011
        template_id: 613
        type: Server
        start_u: 21
        facing: "f"

      - name: comp010
        template_id: 613
        type: Server
        start_u: 20
        facing: "f"

      - name: comp009
        template_id: 613
        type: Server
        start_u: 19
        facing: "f"

      - name: comp008
        template_id: 613
        type: Server
        start_u: 18
        facing: "f"

      - name: comp007
        template_id: 613
        type: Server
        start_u: 17
        facing: "f"

      - name: comp006
        template_id: 613
        type: Server
        start_u: 16
        facing: "f"

      - name: comp005
        template_id: 613
        type: Server
        start_u: 15
        facing: "f"

      - name: comp004
        template_id: 613
        type: Server
        start_u: 14
        facing: "f"

      - name: comp003
        template_id: 613
        type: Server
        start_u: 13
        facing: "f"

      - name: comp002
        template_id: 613
        type: Server
        start_u: 12
        facing: "f"

      - name: comp001
        template_id: 613
        type: Server
        start_u: 11
        facing: "f"

      - name: vdu01
        template_id: 379
        type: MiscellaneousDevice
        start_u: 9
        facing: "f"

      - name: ups01
        template_id: 15
        type: Server
        start_u: 5
        facing: "b"

      - name: storage01
        template_id: 681
        type: Server
        start_u: 1
        facing: "f"

    zero_u_devices:
      - name: pdu01
        template_id: 4
        type: PowerStrip
        location: top
        facing: "b"
        username: fake
        password: fake

      - name: pdu02
        template_id: 4
        type: PowerStrip
        location: top
        facing: "b"
        username: fake
        password: fake

  - name: Rack-2
    u_height: 42

    devices:
      - name: switch02
        template_id: 558
        type: Switch
        start_u: 42
        facing: "b"

      - name: "HP Blade 03"
        template_id: 172
        type: Server
        start_u: 32
        facing: "f"

        devices:
          - name: comp049
            template_id: 172
            type: Server

          - name: comp048
            template_id: 172
            type: Server

          - name: comp047
            template_id: 172
            type: Server

          - name: comp046
            template_id: 172
            type: Server

          - name: comp045
            template_id: 172
            type: Server

          - name: comp044
            template_id: 172
            type: Server

      - name: "HP Blade 02"
        template_id: 172
        type: Server
        start_u: 26
        facing: "f"

        devices:
          - name: comp043
            template_id: 172
            type: Server

          - name: comp042
            template_id: 172
            type: Server

      - name: "HP Blade 01"
        template_id: 172
        type: Server
        start_u: 20
        facing: "f"

        devices:
          - name: comp041
            template_id: 172
            type: Server

          - name: comp040
            template_id: 172
            type: Server

      - name: comp039
        template_id: 613
        type: Server
        start_u: 10
        facing: "f"

      - name: comp038
        template_id: 613
        type: Server
        start_u: 9
        facing: "f"

      - name: comp037
        template_id: 613
        type: Server
        start_u: 8
        facing: "f"

      - name: comp036
        template_id: 613
        type: Server
        start_u: 7
        facing: "f"

      - name: comp035
        template_id: 613
        type: Server
        start_u: 6
        facing: "f"

      - name: comp034
        template_id: 613
        type: Server
        start_u: 5
        facing: "f"

      - name: comp033
        template_id: 613
        type: Server
        start_u: 4
        facing: "f"

      - name: comp032
        template_id: 613
        type: Server
        start_u: 3
        facing: "f"

      - name: comp031
        template_id: 613
        type: Server
        start_u: 2
        facing: "f"

      - name: comp030
        template_id: 613
        type: Server
        start_u: 1
        facing: "f"

    zero_u_devices:
      - name: pdu03
        template_id: 4
        type: PowerStrip
        location: top
        facing: "b"
        username: fake
        password: fake

      - name: pdu04
        template_id: 4
        type: PowerStrip
        location: top
        facing: "b"
        username: fake
        password: fake

data_centre:
  image_path: /ansible/roles/demo-data/files/data_center_background.png
  x_dim: 4
  y_dim: 4

  rack_positions:
    - x_pos: 1.32
      y_pos: 1.42
      x_dim: 0.68
      y_dim: 1.18

    - x_pos: 2.00
      y_pos: 1.42
      x_dim: 0.68
      y_dim: 1.18

  sensor_positions:
    - x_pos: "2.85"
      y_pos: "1.10"
      x_dim: "0.07023411371237458"
      y_dim: "0.07812470935748006"

    - x_pos: "1.05"
      y_pos: "2.85"
      x_dim: "0.07023411371237458"
      y_dim: "0.07812470935748006"

    - x_pos: "1.05"
      y_pos: "1.10"
      x_dim: "0.07023411371237458"
      y_dim: "0.07812470935748006"

    - x_pos: "2.85"
      y_pos: "2.85"
      x_dim: "0.07023411371237458"
      y_dim: "0.07812470935748006"
