sensors: []
non_rack_devices: []

racks:
  - name: Rack-1
    u_height: 42
    template_id: 669
    devices: []
    zero_u_devices: []

data_centre:
  image_path: /ansible/roles/demo-data/files/data_center_background.png
  x_dim: 4
  y_dim: 4

  rack_positions:
    - x_pos: 1.32
      y_pos: 1.42
      x_dim: 0.68
      y_dim: 1.18


  sensor_positions: []

power_cost_bands:
  - name: 'Off peak (am)'
    timefrom: '2000-01-01 00:00:00 UTC'
    timeto:   '2000-01-01 07:00:00 UTC'
    cost_pkwh: 25
    colour: '#82ff37'
    include_days:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - name: 'Peak'
    timefrom: '2000-01-01 07:00:00 UTC'
    timeto:   '2000-01-01 21:00:00 UTC'
    cost_pkwh: 35
    colour: '#ff3d3d'
    include_days:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  - name: 'Off peak (pm)'
    timefrom: '2000-01-01 21:00:00 UTC'
    timeto:   '2000-01-01 23:59:59 UTC'
    cost_pkwh: 25
    colour: '#82ff37'
    include_days:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7

groups: []
inferred_metrics: []
