- name: Disable SNMP (MIB) migrations
  ansible.builtin.command:
    cmd: mv db/migrate/{{ item }} db/migrate/{{ item }}.NOPE
    chdir: "{{ phoenix_modules_root_dir }}/hacor"
  loop: 
    - 106_add_eaton_mibs_to_database.rb
    - 107_add_tpt_mib_to_database.rb
    - 108_add_eaton_mibs_to_database_immutable.rb
