- name: Disable SNMP (MIB) migrations
  ansible.builtin.command:
    cmd: mv db/migrate/{{ item }} db/migrate/{{ item }}.NOPE
    chdir: "{{ rails_root_dir }}/hacor"
    removes: "db/migrate/{{ item }}"
  loop: 
    - 106_add_eaton_mibs_to_database.rb
    - 107_add_tpt_mib_to_database.rb
    - 108_add_eaton_mibs_to_database_immutable.rb


# XXX These should be ported the hacor git repo when that becomes a thing.
- name: Apply patches
  ansible.builtin.patch:
    src: "patches/hacor/{{ item }}"
    basedir: "{{ rails_root_dir }}/hacor"
    backup: yes
    strip: 1
  loop:
    - disable-vpn-and-pxe-config-updating.patch
