- name: Copy template {{ template_src }}
  ansible.builtin.copy:
    src: "{{ template_src }}"
    dest: "{{ template_dest }}"
    remote_src: true

- name: Replace placeholders in {{ template_dest }}
  ansible.builtin.replace:
    path: "{{ template_dest }}"
    regexp: "{{ replacement.regexp }}"
    replace: "{{ replacement.replace }}"
    backup: true
  loop: "{{ replacements }}"
  loop_control:
    loop_var: replacement
