- name: Check for existing installation
  ansible.builtin.command:
    cmd: ls -d {{ emma_path }}
  register: emma_dir
  failed_when: False

- name: Install emma
  when: emma_dir.stdout == ""
  block:
  - name: Download tar file
    ansible.builtin.get_url:
      url: https://api.github.com/repos/alces-flight/concertim-emma/tarball/main
      dest: /tmp/emma.tgz
      headers:
        Authorization: token {{ github_token }}

  - name: Extract tar file
    ansible.builtin.unarchive:
      src: /tmp/emma.tgz
      dest: "{{ rails_root_dir }}"

  - name: Adjust path
    ansible.builtin.shell:
      cmd: |
        mv {{ rails_root_dir }}/alces-flight-concertim-emma-* {{ emma_path }}
        chown -R {{app_user}}:{{app_user}} {{ emma_path }}
      creates: "{{ emma_path }}"

  - name: Sanity check (CT gems)
    ansible.builtin.command:
      cmd: "{{ role_path }}/files/scripts/check_emma_for_ct_gems.sh"
    environment:
      EMMA_CORE_PATH: "{{emma_core_dir}}"

- name: Symlink emma
  ansible.builtin.file:
    src: "{{rails_root_dir}}/emma"
    dest: "/data/private/share/emma"
    state: link

- name: Install configuration
  ansible.builtin.copy:
    src: phoenix-emma.logrotate
    dest: /etc/logrotate.d/phoenix-emma

- name: Bundle install gems
  block:
    # FSR not all of the gems for Emma are included in vendor/cache.  We fix this
    # by copying far too many gems across.
    - name: Vendor missing gems
      ansible.builtin.shell:
        cmd: |
          cp -a {{ playbook_dir }}/roles/gems/files/1.9/*.gem {{ emma_core_dir }}/vendor/cache/
          chown {{app_user}}:{{app_user}} {{ emma_core_dir }}/vendor/cache/*.gem
        executable: /bin/bash

    # XXX The changes should be pushed to the git repo at some point, but its
    # easier to iterate on the build if I'm making changes to a single place.
    - name: Apply patches
      ansible.builtin.patch:
        src: "patches/{{ item }}"
        basedir: "{{ emma_path }}"
        backup: yes
        strip: 1
      loop:
        - update-locked-gems.patch
        - disable-help-links.patch
        - disable-legacy-events-generator.patch
        - disable-vpn-and-pxe-config-updating.patch
        - disable-legacy-events-generator-2.patch
        - nadia-is-not-expected.patch
        - rebranding.patch

    - name: Bundle install gems
      ansible.builtin.shell: |
        cd "{{ emma_core_dir }}"
        PATH={{ruby_19_bin_dir}}:$PATH
        {{ruby_19_bin_dir}}/bundle install --local

    - name: Fix thin to use correct Ruby
      ansible.builtin.replace:
        path: /opt/ruby-1.9/lib/ruby/gems/1.9.1/gems/thin-1.5.1/bin/thin
        regexp: "#!/usr/bin/env ruby"
        replace: "#!/usr/bin/env ruby1.9"

# XXX Move all of these to the emma git repo.
- name: Patch and fixup
  block:
    - name: Monkey patch active record
      ansible.builtin.copy:
        src: monkey_patch_active_record.rb
        dest: "{{ emma_core_dir }}/config/initializers/"
        owner: "{{app_user}}"
        group: "{{app_user}}"
    - name: Load monkey patch when creating database
      ansible.builtin.lineinfile:
        line: "require File.join(Rails.root, 'config/initializers/monkey_patch_active_record')"
        path: "{{ emma_core_dir }}/lib/tasks/database.rake"
        insertbefore: BOF

    - name: Fix issue with DateTime.now
      ansible.builtin.copy:
        src: monkey_patch_date_time_now.rb
        dest: "{{ emma_core_dir }}/config/initializers/"
        owner: "{{app_user}}"
        group: "{{app_user}}"

    - name: Patch config/boot.rb to deal with YAML/psych issue
      ansible.builtin.lineinfile:
        insertbefore: "require 'yaml'"
        line: "Gem.load_yaml"
        state: present
        path: "{{ emma_core_dir }}/config/boot.rb"

    - name: Patch config/boot.rb to deal with YAML/psych issue
      ansible.builtin.lineinfile:
        search_string: "require 'yaml'"
        state: absent
        path: "{{ emma_core_dir }}/config/boot.rb"

    - name: Fix metadata.yml
      ansible.builtin.lineinfile:
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        path: "{{ emma_core_dir }}/config/metadata.yml"
      loop:
        - regexp: '  :build_rev:'
          line:   '  :build_rev: "XXX"'
        - regexp: '  :build_version:'
          line:   '  :build_version: "XXX"'
        - regexp: '  :build_date:'
          line:   '  :build_date: "XXX"'

- name: Create database
  ansible.builtin.shell:
    cmd: |
      PATH={{ruby_19_bin_dir}}:$PATH
      sudo -u "{{app_user}}" --preserve-env=PATH /bin/bash -c 'bundle exec rake db:drop_and_create:emma RAILS_ENV={{ rails_env }} --trace'
    chdir: "{{ emma_core_dir }}"

- name: Populate database
  ansible.builtin.shell:
    cmd: |
      PATH={{ruby_19_bin_dir}}:$PATH
      sudo -u "{{app_user}}" --preserve-env=PATH /bin/bash -c 'bundle exec rake db:migrate:emma RAILS_ENV={{ rails_env }} --trace'
    chdir: "{{ emma_core_dir }}"

- name: Precompile assets
  ansible.builtin.shell:
    cmd: |
      PATH={{ruby_19_bin_dir}}:$PATH
      sudo -u "{{app_user}}" --preserve-env=PATH /bin/bash -c 'bundle exec rake assets:precompile RAILS_ENV={{ rails_env }} --trace'
    chdir: "{{ emma_core_dir }}"

- name: Install tooling
  ansible.builtin.copy:
    src: scaleout-summary.rb
    dest: /usr/local/sbin/
    owner: root
    group: staff
    mode: "755"

- name: Install systemd files
  include_tasks: install_systemd_files.yml
  vars:
    systemd_service_name: emma
    systemd_instance_names: "{{ emma_ports  | join(' ') }}"

- name: Ensure that emma is enabled
  ansible.builtin.service:
    name: emma
    enabled: yes
