- name: Verifying appliance config at "{{ role_path }}/files/tmp/ftsw-data"
  ansible.builtin.shell:
    cmd: |
      if [ ! -f {{ role_path }}/files/tmp/ftsw-data/appliance-config.tgz ] ; then
        cat <<EOF
          Could not find appliance-config.tgz.
          Follow instructions in {{ playbook_dir }}/README.md
      EOF
        exit 1
      fi
  changed_when: False

- name: Verifying appliance setup data at "{{ role_path }}/files/tmp/ftsw-data"
  ansible.builtin.shell:
    cmd: |
      if [ ! -f {{ role_path }}/files/tmp/ftsw-data/setup-data.yml ] ; then
        cat <<EOF
          Could not find setup-data.yml.
          Follow instructions in {{ playbook_dir }}/README.md
      EOF
        exit 1
      fi
  changed_when: False

- name: Copy appliance-config and setup data
  ansible.builtin.copy:
    src:  "{{ item.src }}"
    dest: /usr/src/concurrent-thinking/
    owner: root
    group: root
    mode: "644"
  loop:
    - src: tmp/ftsw-data/appliance-config.tgz
    - src: tmp/ftsw-data/setup-data.yml

- name: Copy FTSW scripts
  ansible.builtin.copy:
    src:  "{{ item }}"
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: "744"
  loop:
    - ftsw-automation.rb
    - ftsw-users.rb
    - setup.sh

- name: Copy FTSW data files
  ansible.builtin.template:
    src:  "{{ item }}"
    dest: /data/private/share/etc/concurrent-thinking/appliance/
    owner: root
    group: "{{app_user}}"
    mode: "640"
  loop:
    - ftsw-user-data.yml

# Failures with the FTSW automation script can be complicated to debug.  The
# following blocks provide more readable error messages should the script fail.
- name: Run FTSW automation script
  block:
    - name: Run FTSW automation script
      ansible.builtin.shell:
        cmd: |
          PATH={{ruby_18_bin_dir}}:$PATH
          sudo -u www-data --preserve-env=PATH /bin/bash -c 'RAILS_ENV={{ rails_env }} script/runner /usr/local/sbin/ftsw-automation.rb'
        chdir: "{{rails_root_dir}}/sas"
      register:
        ftsw_automation
      # The failure will become fatal after the stderr and stdout have been printed.
      ignore_errors: True

    - name: FTSW automation stderr
      ansible.builtin.debug:
        var: ftsw_automation.stderr_lines
      failed_when: ftsw_automation.rc != 0
      ignore_errors: True
      when: ftsw_automation.rc != 0

    - name: FTSW automation stdout
      ansible.builtin.debug:
        var: ftsw_automation.stdout_lines
      failed_when: ftsw_automation.rc != 0
      when: ftsw_automation.rc != 0

- name: Run post migration scripts
  vars:
    post_migration_script_dir: "{{rails_root_dir}}/sas/post_restoration_scripts/always_run"
    post_migration_script: /usr/local/sbin/run_always_run_post_restoration_scripts.rb
  block:
    - name: Run post migration scripts
      ansible.builtin.shell:
        cmd: |
          PATH={{ruby_18_bin_dir}}:$PATH
          sudo -u {{app_user}} --preserve-env=PATH {{post_migration_script}} {{post_migration_script_dir}}
      register: post_migration
      # The failure will become fatal after the stderr and stdout have been printed.
      ignore_errors: True

    - name: post migration scripts stderr
      ansible.builtin.debug:
        var: post_migration.stderr_lines
      failed_when: post_migration.rc != 0
      ignore_errors: true
      when: post_migration.rc != 0

    - name: post migration scripts stdout
      ansible.builtin.debug:
        var: post_migration.stdout_lines
      failed_when: post_migration.rc != 0
      when: post_migration.rc != 0

- name: Configure users
  import_tasks: run_rails_runner.yml
  vars:
    rails_runner: ./bin/rails runner
    runner_args: /usr/local/sbin/ftsw-users.rb
    ruby_bin_dir: "{{ruby_30_bin_dir}}"
    additional_env: ""
    chdir: "{{ rails_root_dir }}/ct-visualisation-app/core"
