- name: Copy user default scripts
  ansible.builtin.template:
    src:  "{{ item }}"
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: "744"
  loop:
    - set-user-defaults.rb

- name: Copy user default data files
  ansible.builtin.template:
    src:  "{{ item }}"
    dest: "{{ct_etc_dir}}"
    owner: root
    group: "{{app_user}}"
    mode: "640"
  loop:
    - default-user-data.yml

- name: Configure users
  import_tasks: run_rails_runner.yml
  vars:
    rails_runner: ./bin/rails runner
    runner_args: /usr/local/sbin/set-user-defaults.rb
    ruby_bin_dir: "{{ruby_30_bin_dir}}"
    additional_env: ""
    chdir: "{{ ct_installation_dir }}/ct-visualisation-app/core"

- name: Create initial rack
  ansible.builtin.shell:
    chdir: "{{ ct_installation_dir }}/ct-visualisation-app/docs/api/examples/"
    cmd: |
      export CONCERTIM_HOST=localhost
      export AUTH_TOKEN=$(LOGIN=admin PASSWORD={{ admin_password }} ./get-auth-token.sh)
      ./create-rack.sh
