- name: Copy FTSW scripts
  ansible.builtin.copy:
    src:  "{{ item }}"
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: "744"
  loop:
    - ftsw-users.rb

- name: Copy FTSW data files
  ansible.builtin.template:
    src:  "{{ item }}"
    dest: /data/private/share/etc/concurrent-thinking/appliance/
    owner: root
    group: "{{app_user}}"
    mode: "640"
  loop:
    - ftsw-user-data.yml

- name: Run post migration scripts
  vars:
    post_migration_script_dir: "{{rails_root_dir}}/sas/post_restoration_scripts/always_run"
    post_migration_script: /usr/local/sbin/run_always_run_post_restoration_scripts.rb
  block:
    - name: Run post migration scripts
      ansible.builtin.shell:
        cmd: |
          PATH={{ruby_18_bin_dir}}:$PATH
          sudo -u {{app_user}} --preserve-env=PATH {{post_migration_script}} {{post_migration_script_dir}}
      register: post_migration
      # The failure will become fatal after the stderr and stdout have been printed.
      ignore_errors: True

    - name: post migration scripts stderr
      ansible.builtin.debug:
        var: post_migration.stderr_lines
      failed_when: post_migration.rc != 0
      ignore_errors: true
      when: post_migration.rc != 0

    - name: post migration scripts stdout
      ansible.builtin.debug:
        var: post_migration.stdout_lines
      failed_when: post_migration.rc != 0
      when: post_migration.rc != 0

- name: Configure users
  import_tasks: run_rails_runner.yml
  vars:
    rails_runner: ./bin/rails runner
    runner_args: /usr/local/sbin/ftsw-users.rb
    ruby_bin_dir: "{{ruby_30_bin_dir}}"
    additional_env: ""
    chdir: "{{ rails_root_dir }}/ct-visualisation-app/core"

- name: Create initial rack
  ansible.builtin.shell:
    chdir: "{{ rails_root_dir }}/ct-visualisation-app/docs/api/examples/"
    cmd: |
      export CONCERTIM_HOST=localhost
      export AUTH_TOKEN=$(LOGIN=admin PASSWORD={{ admin_password }} ./get-auth-token.sh)
      ./create-rack.sh
