- name: Assert credentials have been given
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
      - "{{ item }} != ''"
    fail_msg: "{{ item }} credential has not been given"
    quiet: true
  loop: "{{ credentials }}"

- name: Assert release tag given
  ansible.builtin.assert:
    that:
      - "release_tag is defined"
      - "release_tag != ''"
    fail_msg: "release_tag has not been given"
    quiet: true
