- name: Build docker image
  vars:
    default_build_version: "{{ lookup('vars', component + '_facts_git_tag') | default('') }}"
    default_build_revision: "{{ lookup('vars', component + '_facts_git_sha') | default('') }}"
    default_docker_image_tag: "{{ lookup('vars', component + '_facts_docker_image_tag') | default('') }}"
    default_name: "{{lookup('vars', component).docker_image.name}}"
    default_dockerfile: "{{lookup('vars', component).docker_image.dockerfile | default('Dockerfile')}}"
  community.docker.docker_image:
    name: "{{ name | default(default_name) }}"
    build:
      path: "{{lookup('vars', component).install_dir}}"
      dockerfile: "{{ dockerfile | default(default_dockerfile)}}"
      args:
        BUILD_DATE: "{{ansible_date_time.iso8601}}"
        BUILD_VERSION: "{{ build_version | default(default_build_version) }}"
        BUILD_REVISION: "{{ build_revision | default(default_build_revision) }}"
      network: host
      # http_timeout: 60
    source: build
    tag: "{{ docker_image_tag | default(default_docker_image_tag) }}"
    state: present
    force_source: "{{force_source}}"
  notify: "{{notifications}}"
