- name: Install {{systemd_service_name}} systemd generator
  vars:
    systemd_service_template: /lib/systemd/system/{{ systemd_service_name }}@.service
  ansible.builtin.template:
    src: systemd-generator
    dest: /lib/systemd/system-generators/{{systemd_service_name}}-generator
    owner: root
    group: root
    mode: "755"

- name: Install {{systemd_service_name}}.service
  ansible.builtin.copy:
    src: "{{ systemd_service_name }}.service"
    dest: /lib/systemd/system/{{ systemd_service_name }}.service
    owner: root
    group: root
    mode: "644"

- name: Install {{systemd_service_name}}@.service template
  ansible.builtin.template:
    src: "{{ systemd_service_name }}@.service"
    dest: /lib/systemd/system/{{ systemd_service_name }}@.service
    owner: root
    group: root
    mode: "644"
