- name: Run rake task
  ansible.builtin.shell:
    cmd: |
      PATH={{ruby_bin_dir}}:$PATH
      RAILS_ENV={{ rails_env }}
      sudo -u {{ app_user }} --preserve-env=PATH,RAILS_ENV /bin/bash -c '{{additional_env}} rake {{rake_task}} --trace'
    chdir: "{{chdir}}"
