- name: Install mongrel gems
  ansible.builtin.command:
    cmd: gem1.8 install "{{ role_path }}/files/{{ item }}*.gem" --no-rdoc --no-ri --local
  loop:
    - gem_plugin
    - daemons
    - fastthread
    - cgi_multipart_eof_fix
    - mongrel-1.1.3   # Include version to increase specificity of the glob.
    - mongrel_cluster

- name: Install init.d file
  ansible.builtin.template:
    src: "mongrel_cluster.init"
    dest: "/etc/init.d/mongrel_cluster"
    owner: root
    group: root
    mode: "744"

- name: Make pid directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - path: "{{ mongrel_pid_dir }}"
      owner: "{{ mongrel_user }}"
      group: root
      mode: u=rwx,g=rx,o=rx
    - path: "{{ mongrel_conf_dir }}"
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx

- name: Link binaries
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - src: "{{ gem_18_bin_dir }}/mongrel_cluster_ctl"
      dest: /usr/sbin/mongrel_cluster_ctl
    - src: "{{ gem_18_bin_dir }}/mongrel_rails"
      dest: /usr/sbin/mongrel_rails

- name: Clear romance log for monit reasons
  block:
    - name: Install mongrel rails clear
      ansible.builtin.copy:
        src: mongrel_rails_clear
        dest: /usr/sbin
        owner: root
        group: root
        mode: "755"

    - name: mongrel_rails clears logs
      ansible.builtin.lineinfile:
        path: /usr/sbin/mongrel_rails
        insertafter: 'require.*rubygems'
        firstmatch: yes
        line: 'system("/usr/sbin/mongrel_rails_clear #{ARGV.join(" ")}")'
