- name: Generate shared secret
  vars:
    secret_file: "{{ct_etc_dir}}/secret"
  block:
    - name: Create secret
      ansible.builtin.shell:
        cmd: |
          ruby -r securerandom -e 'puts SecureRandom.hex(64)' > {{secret_file}}

    - name: Ensure {{app_user}} can read file
      ansible.builtin.file:
        path: "{{secret_file}}"
        owner: root
        group: "{{app_user}}"
        mode: "640"
