#!/bin/bash

# Takes the mongrel daemon as first argument and just kills it until its gone
# Can be used for: scram sian hacor nadia uma meca sas oobm
# Not sure if its OK for mia with its 3 daemons, needs more testing before incorporating for mia

daemon=${1}

while true
do 
   pid=$(pgrep -f "${daemon} --user")
   if [ "${pid}" != "" ]; then 
      kill -9 ${pid}
   else 
      break
   fi
   sleep 2
done

# eof
