- name: Restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    # Rails apps
    - phoenix-mongrel
    - emma
    - ct-visualisation-app
    #
    # Daemons
    - ailsa
    - enid
    - maggie
    - martha
    - meryl
    - theresa
    - ct-capacity-daemon
    - metric-reporting-daemon
    #
    # Other daemons 
    - delayed_job

- name: Restart delia service
  block:
    # XXX Figure something better than this.
    - name: Wait for other services to start
      ansible.builtin.wait_for:
        timeout: 60

    - name: Restart delia
      ansible.builtin.service:
        name: delia
        state: restarted

    # XXX Figure something better than this.
    - name: Give delia a moment or two
      ansible.builtin.wait_for:
        timeout: 60

# We can now stop the legacy services.
- name: Stop legacy services
  ansible.builtin.service:
    name: "{{item}}"
    state: stopped
    enabled: no
  loop:
    - phoenix-mongrel
    - emma
    - delayed_job
    - delia

    - ailsa
    - enid
    - maggie
    - martha
    - theresa
    - ct-capacity-daemon
  when: finalization_stop_legacy_services == True

# We're now finally ready to monit our services.
- name: Start monit
  ansible.builtin.service:
    name: monit
    state: restarted
    enabled: yes
  when: finalization_start_monit == True
