- name: Restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - ct-visualisation-app
    - meryl
    - metric-reporting-daemon
    - ct-visualisation-job-runner

# We're now finally ready to monit our services.
- name: Start monit
  ansible.builtin.service:
    name: monit
    state: restarted
    enabled: yes
