- name: Restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  vars:
    services:
      - memcached
      - ct-metric-reporting-daemon
      - ct-metric-processing-daemon
      - "{{ (not want_dev_build) | ternary('ct-visualisation-app', '') }}"
      - "{{ (not want_dev_build) | ternary('ct-visualisation-job-runner', '') }}"
  loop: "{{ services | select | list }}"

# We're now finally ready to monit our services.
- name: Start monit
  ansible.builtin.service:
    name: monit
    state: restarted
    enabled: yes
