- name: Ensure docker secrets exist
  ansible.builtin.set_fact:
    db_password: "{{ lookup('password', '{{ct_docker_dir}}/secrets/db-password chars=ascii_letters,digits length=32') }}"
    rails_master_key: "{{ lookup('password', '{{ct_docker_dir}}/secrets/rails-master-key chars=ascii_letters,digits length=32') }}"
    redis_password: "{{ lookup('password', '{{ct_docker_dir}}/secrets/redis-password chars=ascii_letters,digits length=32') }}"

- name: Create secrets env file
  ansible.builtin.template:
    src: secrets.env
    dest: "{{ct_docker_dir}}/secrets"
    owner: root
    group: root
    mode: '0600'
    lstrip_blocks: yes
