version: '3.3'
volumes:
  db:
services:
  killbill:
    image: killbill/killbill:0.24.0
    ports:
      - "{{killbill_interface}}:{{killbill_port}}:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:postgresql://db:5432/killbill
      - KILLBILL_DAO_USER=postgres
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
  kaui:
    image: killbill/kaui:2.0.11
    ports:
      - "{{kaui_interface}}:{{kaui_port}}:8080"
    environment:
      - KAUI_DB_ADAPTER=postgresql
      - KAUI_CONFIG_DAO_URL=jdbc:postgresql://db:5432/kaui
      - KAUI_CONFIG_DAO_USER=postgres
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
  db:
    image: killbill/postgresql:0.24
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=killbill
