- name: Install postgresql
  register: result
  until: result is success
  ansible.builtin.apt:
    name: postgresql
    state: present

- name: Ensure that postgresql is started
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes
