ct_vis_app_path: "{{ ct_installation_dir }}/ct-visualisation-app"
ct_vis_app_core_dir: "{{ ct_installation_dir }}/ct-visualisation-app/core"
ct_vis_app_log_file: /var/log/ct-visualisation-app.log

admin_password: admin
admin_email: admin@test.com
operator_password: operator
operator_email: operator@test.com
