---
- name: Build and configure an Alces Concertim machine
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  pre_tasks:
    - name: Check credentials and release tag
      vars:
        credentials:
          - aws_access_key_id
          - aws_secret_access_key
      include_tasks: tasks/assert_credentials_and_release_tag.yml

  roles:
    - role: misc_packages
      tags: misc_packages
    - role: webserver
      tags: webserver
    - role: database
      tags: database
    - role: memcached
      tags: memcached
    - role: ganglia
      tags: ganglia
    - role: monit
      tags: monit
    - role: data_dirs
      tags: data_dirs
    - role: metric-reporting
      tags: metric-reporting
    - role: ct-visualisation-app
      tags: ct-visualisation-app
    - role: appliance-dev
      tags: appliance-dev
      when: want_dev_build | bool
    - role: fake-gmond
      tags: fake-gmond
      when: want_fake_metrics | bool
    - role: licence-limits
      tags: licence-limits
    - role: finalization
      tags: finalization
