---
- name: Build and configure an Alces Concertim machine
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: build_base
    - role: misc_packages
      tags: misc_packages
    - role: webserver
      tags: webserver
    - role: database
      tags: database

    # XXX Currently only used for running hacor db migrations beanstalkd.
    - role: beanstalkd
      tags: beanstalkd

    - role: memcached
      tags: memcached
    - role: ganglia
      tags: ganglia
    - role: monit
      tags: monit
    - role: data_dirs
      tags: data_dirs
    - role: ruby
      tags: ruby
    - role: gems
      tags: gems

    # XXX Want to get rid of this as soon as we can.
    - role: snmp
      tags: snmp

    - role: package-daemons
      tags: package-daemons

    # XXX Currently want these for migrations and post migraiton scripts.
    # The chassis templates in hacor are part of that.
    - role: phoenix-modules
      tags: phoenix-modules

    - role: ct-visualisation-app
      tags: ct-visualisation-app
    - role: personality
      tags: personality
    - role: release-info
      tags: release-info
    - role: appliance-dev
      tags: appliance-dev
      when: want_dev_build | bool
    - role: fake-gmond
      tags: fake-gmond
      when: want_fake_metrics | bool
    - role: configure-vanilla
      tags: configure-vanilla
    - role: license-limits
      tags: license-limits
    - role: finalization
      tags: finalization
