---
- name: Build machine to be an unconfigured (vanilla) Flight Concertim MIA
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: base
    - role: misc_packages
      tags: misc_packages
    # - role: certificates
    #   tags: certificates
    - role: webserver
      tags: webserver
    - role: database
      tags: database
    - role: beanstalkd
      tags: beanstalkd
    - role: memcached
      tags: memcached
    - role: ganglia
      tags: ganglia
    # - role: monit
    #   tags: monit
    - role: data_dirs
      tags: data_dirs
    - role: ruby
      tags: ruby
    - role: gems
      tags: gems
    - role: snmp
      tags: snmp
    - role: phoenix-mongrel
      tags: phoenix-mongrel
    - role: delia
      tags: delia
    - role: delia-plugins
      tags: [delia, delia-plugins]
    - role: package-daemons
      tags: package-daemons
    - role: phoenix-modules
      tags: phoenix-modules
    - role: emma
      tags: emma
    - role: package-mia
      tags: [package-mia, mia]
    - role: release-info
      tags: release-info
    - role: appliance-dev
      tags: appliance-dev
    - role: finalization
      tags: finalization

#
# - gmetad-agg (???)
# - gmetad-sync (???)
