---
- name: Build and configure an Alces Concertim machine
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  vars:
    docker_build: false

  pre_tasks:
    - name: Check credentials and release tag
      tags: prep
      vars:
        credentials:
          - aws_access_key_id
          - aws_secret_access_key
      include_tasks: tasks/assert_credentials_and_release_tag.yml

    - name: Make installation directories
      tags: prep
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        state: directory
      loop:
        - path: "{{ct_root_dir}}"
          owner: root
          group: root
          mode: "755"

        - path: "{{ct_etc_dir}}"
          owner: root
          group: root
          mode: "755"

        - path: "{{ct_installation_dir}}"
          owner: "{{app_user}}"
          group: "{{app_user}}"
          mode: "755"

    - name: Install dependencies for ansible S3 tasks
      tags: prep
      register: result
      until: result is success
      ansible.builtin.apt:
        name: python3-boto3
        state: latest

  roles:
    - role: webserver
      tags: webserver
    - role: database
      tags: database
      when: not docker_build | bool
    - role: ganglia
      tags: ganglia
    - role: metric-reporting
      tags: metric-reporting
    - role: ct-visualisation-app
      tags: ct-visualisation-app
    - role: appliance-dev
      tags: appliance-dev
      when: want_dev_build | bool
    - role: monit
      tags: monit
      when: not docker_build | bool
