---
- name: Configure an unconfigured (vanilla) Flight Concertim MIA
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars:
    finalization_start_monit: true
    finalization_stop_legacy_services: true
  roles:
    - role: configure-vanilla
      tags: configure-vanilla
    - role: license-limits
      tags: license-limits
    - role: finalization
      tags: finalization
