---
- name: |
    Playbook to build, package and upload assets required by Alces Concertim.

    Alces Concertim has a number of assets that need to be built on a machine
    similar to the Concertim machine itself.  Such as `ruby` versions `1.8` and
    `1.9` and some C++ Ruby extensions, aka "number crunchers".  Also the
    daemons, modules and appliances need packaging.

    This playbook builds them, packages them and uploads them to S3.
  hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  vars:
    # The directory where built packages are placed.
    package_assets_package_dir: /tmp/concertim/package-assets/packages
    # The directory where the build takes place.
    package_assets_repo_dir: /tmp/concertim/package-assets/repos
    remove_prior_builds: true
    dryrun: true
  roles:
    - role: package-base
    - role: package-assets
