---
- name: |
    Playbook to build, package and upload assets required by Alces Concertim.

    Alces Concertim has a number of assets that are to be built on a machine
    similar to the Concertim machine itself. This playbook builds them,
    packages them and uploads them to S3.
  hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  vars:
    # The directory where built packages are placed.
    package_assets_package_dir: /tmp/concertim/package-assets/packages
    # The directory where the build takes place.
    package_assets_repo_dir: /tmp/concertim/package-assets/repos
    remove_prior_builds: true
    dryrun: true

  pre_tasks:
    - name: Check credentials and release tag
      vars:
        credentials:
          - gh_token
          - aws_access_key_id
          - aws_secret_access_key
      include_tasks: tasks/assert_credentials_and_release_tag.yml

  roles:
    - role: package-assets
