---
- name: Configure machine to be a Flight Concertim MIA
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: False
  roles:
    - base
    # - certificates
    - webserver
    - database
    - beanstalkd
    - memcached
    - ganglia
    # - smp
    # - wmi
    - data_dirs
    - ruby
    - gems
    - delia
    - phoenix-modules
    - emma

#
# - monit (???)
# - gmetad-agg (???)
# - gmetad-sync (???)

# ---
#
# - delayed_job: an emma thing. it runs jobs in the background.
