---
- name: Install and build Alces Concertim components as docker containers
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  vars:
    ct_action: deploy

  pre_tasks:
    - name: Assert credentials are present
      ansible.builtin.assert:
        that:
          - "{{ item }} is defined"
          - "{{ item }} != ''"
        fail_msg: "{{ item }} credential has not been given"
        quiet: true
      loop:
        - gh_token

    - name: Make installation directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        state: directory
      loop:
        - path: "{{ct_root_dir}}"
          owner: root
          group: root
          mode: "755"
        - path: "{{ct_etc_dir}}"
          owner: root
          group: root
          mode: "755"
        - path: "{{ct_installation_dir}}"
          owner: root
          group: root
          mode: "755"
        - path: "{{ct_log_dir}}"
          owner: root
          group: root
          mode: "755"
        - path: "{{ct_var_lib_dir}}"
          owner: root
          group: root
          mode: "755"
        - path: "{{ct_docker_dir}}"
          owner: root
          group: root
          mode: "755"
        - path: "{{ct_docker_dir}}/secrets"
          owner: root
          group: root
          mode: "700"

  roles:
    - role: concertim_common
      tags: concertim
      when: enable_concertim | bool

    - role: db
      tags: concertim
      when: enable_concertim | bool

    - role: proxy
      tags: concertim
      when: enable_concertim | bool

    - role: metric_reporting_daemon
      tags: concertim
      when: enable_concertim | bool

    - role: visualisation_app
      tags: concertim
      when: enable_concertim | bool

    - role: cluster_builder
      tags: cluster_builder
      when: enable_cluster_builder | bool

    - role: killbill
      tags: killbill
      when: enable_killbill | bool

    - role: openstack_service
      tags: openstack_service
      when: enable_openstack_service | bool

  tasks:
    - name: Install docker compose file
      ansible.builtin.template:
        src: docker-compose.yml
        dest: "{{ct_docker_dir}}/"

# Run any tasks that need to run after all of the containers and the docker
# compose configuration is in place.  E.g., migrating databases.
- name: Post-install configuration of Alces Concertim components
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars:
    ct_action: post-deploy
  roles:
    - role: visualisation_app
      tags: concertim
      when: enable_concertim | bool

- name: Start Alces Concertim components
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    # Ensure all services are up.  If any needed restarting they will have been
    # downed in the previous plays, all that needs to happen here is ensure
    # they're up.
    - name: Start concertim services
      tags:
        - concertim
        - cluster_builder
        - openstack_service
      when: (enable_concertim | bool) or (enable_cluster_builder | bool) or (enable_openstack_service | bool)
      ansible.builtin.shell:
        chdir: "{{ct_docker_dir}}"
        cmd: |
          docker compose up --detach

    - name: Start killbill
      tags: killbill
      when: enable_killbill | bool
      ansible.builtin.shell:
        chdir: "{{ct_installation_dir}}/killbill"
        cmd: |
          docker compose up --detach
