---
- name: Prepare a machine to be built into an unconfigured (vanilla) Flight Concertim MIA
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  roles:
    - role: use-eth0-naming
      tags: use-eth0-naming

