- name: Check for existing installation of node
  ansible.builtin.shell: node -v
  register: node_version
  ignore_errors: true

- name: Install dependencies and node
  block:
    - name: Run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required tools
      register: result
      until: result is success
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Make keyrings directory
      ansible.builtin.file:
        path: "/etc/apt/keyrings"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "755"
        state: directory

    - name: import the Nodesource GPG key
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key |
        sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

    - name: create deb repository
      vars:
        NODE_MAJOR: 20
      register: result
      until: result is success
      ansible.builtin.shell: |
        echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ NODE_MAJOR }}.x nodistro main" |
        sudo tee /etc/apt/sources.list.d/nodesource.list

    - name: Run the equivalent of "apt-get update"
      ansible.builtin.apt:
        update_cache: yes

    - name: Install node js
      register: result
      until: result is success
      ansible.builtin.apt:
        name:
          - nodejs
        state: present
  when: node_version.stdout.find('v20') == -1
