- name: Install useful dev tools
  register: result
  until: result is success
  ansible.builtin.apt:
    name:
      - golang-go
      - net-tools
      - ruby3.0
      - jq
    state: latest

# As above, install scripts that are for development.  Scripts that are useful
# for production debugging and maintenance should be installed by the
# misc-packages role.
- name: Install useful dev scripts
  ansible.builtin.copy:
    src: scripts/
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: "0755"

- name: Generate shared secret
  vars:
    secret_file: "{{ct_etc_dir}}/secret"
  block:
    - name: Create secret
      ansible.builtin.shell:
        cmd: |
          ruby -r securerandom -e 'puts SecureRandom.hex(64)' > {{secret_file}}

    - name: Ensure {{app_user}} can read file
      ansible.builtin.file:
        path: "{{secret_file}}"
        owner: root
        group: "{{app_user}}"
        mode: "640"

- name: Install Node
  include_tasks: install_node.yml

- name: Install yarn
  include_tasks: install_yarn.yml

- name: Nginx dev configuration
  include_tasks: nginx_dev_configuration.yml

- name: Configure trusted access to database
  include_tasks: database_trusted_access.yml

- name: Setup dev ct-visualisation-app
  include_tasks: setup_dev_ct_vis_app.yml

- name: Setup dev metric daemons
  include_tasks: setup_dev_metric_daemon.yml
