- name: Disable production document root
  vars:
    document_root: /etc/nginx/snippets/server-https.d/document-root.conf
  ansible.builtin.shell:
    cmd: |
      if [ ! -f {{document_root}} -a -f {{document_root}}.disabled ] ; then
        # Looks like we've already ran this.
        :
      else
        mv {{document_root}} {{document_root}}.disabled
      fi

- name: Install dev document root
  ansible.builtin.template:
    src: document-root-dev.conf
    dest: /etc/nginx/snippets/server-https.d/

- name: Disable nginx serving of assets
  vars:
    assets_config: /etc/nginx/snippets/server-https.d/ct-visualisation-assets.conf
  ansible.builtin.shell:
    cmd: |
      if [ ! -f {{assets_config}} -a -f {{assets_config}}.disabled ] ; then
        # Looks like we've already ran this.
        :
      else
        mv {{assets_config}} {{assets_config}}.disabled
      fi

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
