- name: Check for dev installation
  ansible.builtin.command:
    cmd: ls -d {{dev_root_dir}}/ct-visualisation-app
  register: dev_ct_vis_dir
  failed_when: False


- name: Bundle install gems for dev ct-visualisation-app
  ansible.builtin.shell: |
    cd {{dev_root_dir}}/ct-visualisation-app/
    ./bin/bundle install
  when: dev_ct_vis_dir.stdout != ""

- name: Install yarn dependencies
  ansible.builtin.shell: |
    cd {{dev_root_dir}}/ct-visualisation-app/
    yarn

# - name: unmonitor ct-vis-app
#   ansible.builtin.command:
#     cmd: monit unmonitor ct-visualisation-app


- name: Disable production ct-visualisation-app
  ansible.builtin.service:
    name: "{{item}}"
    state: stopped
    enabled: no
  loop:
    - ct-visualisation-app
    - ct-visualisation-job-runner


- name: Workaround git and vboxfs issue
  ansible.builtin.command:
    cmd: git config --global --add safe.directory /opt/concertim/dev/ct-visualisation-app

- name: Create database
  vars:
    task: db:create
  ansible.builtin.shell:
    cmd: |
      sudo -u root /bin/bash -c 'RAILS_ENV=development ./bin/rails {{task}} --trace'
    chdir: "{{dev_root_dir}}/ct-visualisation-app/"

- name: Migrate database
  vars:
    task: db:migrate
  ansible.builtin.shell:
    cmd: |
      sudo -u root /bin/bash -c 'RAILS_ENV=development ./bin/rails {{task}} --trace'
    chdir: "{{dev_root_dir}}/ct-visualisation-app/"

- name: Start dev server
  ansible.builtin.command:
    cmd: screen -dmS ct-vis-app ./bin/dev
    chdir: "{{dev_root_dir}}/ct-visualisation-app/"

- name: Create dev templates
  block:
    - name: Wait for dev server to start
      ansible.builtin.pause:
        seconds: 30

    - name: Run populate templates script
      ansible.builtin.shell:
        chdir: "{{dev_root_dir}}/ct-visualisation-app/docs/api/examples"
        cmd: |
          export CONCERTIM_HOST=localhost
          export AUTH_TOKEN=$(LOGIN=admin PASSWORD=admin ./get-auth-token.sh)
          if [ $(./list-templates.sh | jq 'length') -eq 0 ] ; then
            echo "Populating dev templates"
            ./populate-templates.sh
          else
            echo "Templates previously populated"
          fi
