# Install tools that are for production debugging and maintenance. Tools
# strictly for development should be installed by the appliance-dev role.
- name: Install useful utilities
  register: result
  until: result is success
  ansible.builtin.apt:
    name:
      - net-tools
      - jq
    state: latest
