#!/bin/bash
release=/etc/concurrent-thinking/appliance/release.yml

# Turn this appliance into one where command processes everything (simulated data)
grep "simulated: true" ${release} > /dev/null
if [ $? = "1" ]; then
   # Is there already an entry and is it set to false
   grep "simulated: false" ${release} > /dev/null
   if [ $? = "0" ]; then
      sed -i 's/simulated: false/simulated: true/' ${release}
      echo "Updated simulated data field in ${release}"
   else
      echo "simulated: true" >>  ${release}
      echo "Added simulated data field to ${release}"
   fi
   /etc/init.d/delayed_job restart
fi

# XXX Disable deamons and cron jobs that we don't want running in demo mode.

##################################################################

# Launch the bit that alters the data
./run_demo demo3 &

# stop ganglia as fake-gmond uses same port
# service ganglia-monitor stop > /dev/null
# Now gmond is monitored by monit we need to tell monit to stop it
# No need to shut this down now I have moved to port 8677, same port as Bens so already in /etc/gmetad.conf
#monit stop gmond

touch fake_gmond_started

# This generates a new gmond.out takes about 30-45 secs based on number of nodes and  sleeps for N secs
# delete the old one before you start...
rm -f ./gmond.out
./dumpdata.sh &

# Let the first gmond.out get generated before we load the fake gmond
# This just modifys timestamp and sends it into ganglia stream
# Loop until the file is created then drop out.....
(while [ ! -f ./gmond.out ]; do
   sleep 5
done
./fake-gmond.rb )&

# Just in case there are issues we now log certain system data to a resources file
# No need to run this unless we are investigating an issue......
# ./check_system_resources.sh &

echo "This is what is running in the background"
jobs
