- name: Make destination directory
  ansible.builtin.file:
    path: "{{ fake_gmond_extract_dir }}"
    owner: "{{ fake_gmond_owner }}"
    group: "{{ fake_gmond_group }}"
    mode: "755"
    state: directory

- name: Install fake-gmond tarball from s3
  vars:
    destination_dir: "{{ fake_gmond_extract_dir }}"
    s3_prefix: "{{fake_gmond_s3_prefix}}"
    tarball_name: "{{fake_gmond_tarball_name}}"
    untarred_dir: "{{fake_gmond_untarred_dir}}"
    correct_owner: "{{fake_gmond_owner}}"
    correct_group: "{{fake_gmond_group}}"
  include_tasks: install_s3_tarball.yml

# XXX Move to fake gmond git repo when available.
- name: Patch source code
  ansible.builtin.patch:
    src: "patches/{{ item }}"
    basedir: "{{ fake_gmond_src_dir }}"
    backup: yes
    strip: 1
  loop:
    - fix-ruby-path.patch
    - remove-in-band-metrics.patch
    - rework-example-metrics.patch

# XXX Move to fake gmond git repo when available.
- name: Install start_fake_gmond script
  ansible.builtin.copy:
    src: start_fake_gmond
    dest: "{{ fake_gmond_src_dir }}"
    owner: "{{ fake_gmond_owner }}"
    group: "{{ fake_gmond_group }}"
    mode: "755"

- name: Install init.d file
  ansible.builtin.copy:
    src: fake-ganglia.init
    dest: /etc/init.d/fake-ganglia
    owner: root
    group: root
    mode: "755"

- name: Add entry to gmetad.conf
  ansible.builtin.lineinfile:
    line: "data_source fake_gmond localhost:{{ fake_gmond_port }}"
    path: /etc/ganglia/gmetad.conf
    insertbefore: EOF
  register: gmetad_change

- name: Restart gmetad
  ansible.builtin.service:
    name: gmetad
    state: restarted
  when: gmetad_change.changed

- name: Ensure fake gmond is enabled
  ansible.builtin.service:
    name: fake-ganglia
    state: started
    enabled: yes

