- name: Ensure ganglia is at the latest version
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - ganglia-monitor
    - gmetad
    - rrdtool

- name: Install gmetad-agg
  vars:
    download_dest: "{{ role_path }}/files/tmp/{{ gmetad_agg_deb }}"
  block:
    - name: Download gmetad-agg from S3
      amazon.aws.aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ debs_prefix }}{{ gmetad_agg_deb }}"
        dest: "{{ download_dest }}"
        mode: get
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"

    - name: Install gmetad-agg deb
      ansible.builtin.apt:
        deb: "{{ download_dest }}"

- name: Install gmond configuration
  ansible.builtin.copy:
    src: gmond.conf
    dest: /etc/ganglia/gmond.conf.alces
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Install gmetad configuration
  ansible.builtin.copy:
    src: gmetad.conf
    dest: /etc/ganglia/
    owner: root
    group: nogroup
    mode: u=rw,g=r,o=r

- name: Install gmetad-agg configuration
  ansible.builtin.copy:
    src: gmetad-agg.conf
    dest: /etc/ganglia/
    owner: root
    group: nogroup
    mode: u=rw,g=r,o=r

- name: Install rrd file age monitoring script
  block:
    - name: Install script
      ansible.builtin.copy:
        src: check_rrd_age.sh
        dest: /usr/local/sbin/
        mode: "755"
        owner: root
        group: root

    - name: Create symlinks
      ansible.builtin.file:
        src: /usr/local/sbin/check_rrd_age.sh
        dest: "/usr/local/sbin/{{ item }}"
        state: link
      loop:
        - check_gmetad_rrd_age.sh
        - check_gmetad-agg_rrd_age.sh

- name: Ensure that ganglia is started
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - ganglia-monitor
    - gmetad
    - gmetad-agg
