- name: Install gmetad and rrdtool
  register: result
  until: result is success
  ansible.builtin.apt:
    name:
      - gmetad
      - rrdtool
    state: latest

- name: Install gmetad configuration
  ansible.builtin.copy:
    src: gmetad.conf
    dest: /etc/ganglia/
    owner: root
    group: nogroup
    mode: u=rw,g=r,o=r

- name: Ensure that gmetad is started
  ansible.builtin.service:
    name: gmetad
    state: restarted
    enabled: yes
  when: not docker_build | bool
