- name: Create empty placeholder directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - path: /data/private/share/snmp-system
      owner: www-data
      group: www-data
      mode: u=rwx,g=rwx,o=rx

    - path: /data/private/share/snmp-system/mibs
      owner: www-data
      group: www-data
      mode: u=rwx,g=rwx,o=rx

    - path: /data/private/share/snmp
      owner: www-data
      group: www-data
      mode: u=rwx,g=rwx,o=rx

    - path: /data/private/share/snmp/mibs
      owner: www-data
      group: www-data
      mode: u=rwx,g=rwx,o=rx

